import json
from datetime import datetime

import pandas as pd
import streamlit as st


# ---------------------------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------------------------

st.set_page_config(
    page_title="DPIA-based Fundamental Rights Assessment Tool",
    layout="wide"
)

st.title("DPIA-based Fundamental Rights Assessment Tool")
st.caption(
    "A DPIA-based workflow for fundamental-rights risk assessment, with "
    "role-triggered AI Act modules for providers and deployers."
)

st.markdown(
    """
    **Created by F. Paolucci for DIGCON - FIS-funded project, Baffi Centre, Bocconi University**  
    **All rights reserved**
    """
)

st.info(
    "Research prototype. Do not enter personal data, confidential DPIAs, trade secrets, "
    "or sensitive organisational information. Use fictional or fully anonymised cases."
)


# ---------------------------------------------------------------------
# OPTIONS
# ---------------------------------------------------------------------

FILER_ROLES = [
    "Controller / data protection team",
    "Provider",
    "Deployer",
    "Joint assessment team",
    "Other"
]

YES_NO_OPTIONS = ["Yes", "No", "Partly", "To be verified"]
YES_NO_NA_OPTIONS = ["Yes", "No", "Partly", "Not applicable", "To be verified"]
EVIDENCE_OPTIONS = [
    "Yes",
    "No",
    "Partly",
    "Not known to this filer",
    "Information to be requested",
    "Not applicable",
    "To be verified"
]

RISK_LEVELS = ["Low", "Medium", "High", "Very high", "To be verified"]
FREQUENCY_OPTIONS = ["One-off", "Occasional", "Regular", "Continuous", "To be verified"]

CONTEXTS = [
    "Employment/HR",
    "Education",
    "Credit/insurance",
    "Welfare/public services",
    "Healthcare",
    "Justice/policing/migration",
    "Platforms/content",
    "Marketing/CRM",
    "Physical security/access",
    "Other"
]

ACTIONS = [
    "Scoring/ranking",
    "Classification",
    "Recommendation",
    "Exclusion/de-prioritisation",
    "Monitoring/surveillance",
    "Identity verification/biometrics",
    "Content moderation/ranking",
    "Risk prediction",
    "Content generation",
    "Other"
]

DATA_CATEGORIES = [
    "No personal data",
    "Common personal data",
    "Special categories of data",
    "Biometric data",
    "Inferred/profiling data",
    "Behavioural data",
    "Data from multiple sources",
    "Proxy variables",
    "Children's data"
]

DATA_SOURCES = [
    "Directly provided by the data subject",
    "Generated by the organisation",
    "Third-party data",
    "Publicly available data",
    "Sensor/IoT/log data",
    "Inferred data",
    "Combined datasets",
    "Other"
]

DECISION_EFFECTS = [
    "No significant effect",
    "Support to human decision",
    "Legal or similarly significant effect",
    "Access/exclusion/priority in services or opportunities"
]

GROUPS = [
    "Workers/candidates",
    "Students",
    "Patients",
    "Welfare beneficiaries",
    "Consumers",
    "Children",
    "Migrants/asylum seekers",
    "Persons with disabilities",
    "Protected or vulnerable groups",
    "General public"
]

LEGAL_BASES = [
    "To be determined",
    "Consent",
    "Contract",
    "Legal obligation",
    "Public interest",
    "Legitimate interest",
    "Vital interests",
    "Not applicable / to be verified"
]

DATA_SUBJECT_RIGHTS = [
    "Access",
    "Rectification",
    "Erasure",
    "Restriction",
    "Objection",
    "Portability",
    "Right not to be subject to solely automated decision-making where applicable",
    "Human intervention where applicable",
    "None / to be defined"
]

DATA_QUALITY_MEASURES = [
    "Data relevance check",
    "Data accuracy check",
    "Data completeness check",
    "Representativeness assessment",
    "Bias/proxy-variable analysis",
    "Outdated data removal",
    "Data lineage documentation",
    "Training/validation/test data separation",
    "Error correction procedure",
    "Ongoing data quality monitoring",
    "None / to be defined"
]

HUMAN_OVERSIGHT_MEASURES = [
    "Human-in-the-loop before final decision",
    "Human-on-the-loop monitoring",
    "Human override power",
    "Mandatory review for adverse outcomes",
    "Escalation to qualified reviewer",
    "Training against automation bias",
    "Documentation of human review",
    "Time and authority to depart from system output",
    "Periodic audit of human decisions",
    "None / to be defined"
]

CONTESTABILITY_MEASURES = [
    "Individual notice of AI-assisted decision",
    "Meaningful explanation of outcome",
    "Accessible complaint channel",
    "Human review upon request",
    "Possibility to correct input data",
    "Possibility to submit additional evidence",
    "Reasoned response to complaint",
    "Defined response deadlines",
    "Reversal or correction of adverse outcome",
    "Escalation to independent body or DPO",
    "None / to be defined"
]

GOVERNANCE_DECISIONS = [
    "GO",
    "CONDITIONAL GO",
    "REDESIGN REQUIRED",
    "NO-GO",
    "ESCALATE FOR REVIEW",
    "To be decided"
]

ACTION_STATUSES = ["To be started", "In progress", "Completed", "Not applicable", "Blocked"]


# ---------------------------------------------------------------------
# FUNDAMENTAL-RIGHTS RISK CATALOGUE
# ---------------------------------------------------------------------

RISK_CATALOG = [
    {
        "id": "FR1",
        "risk": "Excessive or disproportionate data processing",
        "rights": "Privacy; data protection; informational self-determination",
        "triggers": {"data_categories": ["Common personal data", "Special categories of data", "Biometric data", "Inferred/profiling data", "Behavioural data", "Data from multiple sources", "Children's data"]},
        "mechanisms": "Data minimisation failure; purpose creep; invisible inference; excessive retention; unexpected data combination",
        "safeguards": "Data minimisation; purpose limitation; retention limits; clear information notice; effective data-subject rights"
    },
    {
        "id": "FR2",
        "risk": "Direct, indirect or proxy discrimination",
        "rights": "Equality; non-discrimination; equal access to opportunities",
        "triggers": {"contexts": ["Employment/HR", "Education", "Credit/insurance", "Welfare/public services", "Healthcare", "Justice/policing/migration"], "actions": ["Scoring/ranking", "Classification", "Exclusion/de-prioritisation", "Risk prediction"], "data_categories": ["Special categories of data", "Biometric data", "Proxy variables", "Inferred/profiling data"]},
        "mechanisms": "Historical bias; proxy variables; unequal error rates; under-representation; disparate impact",
        "safeguards": "Bias testing; subgroup analysis; independent audit; proxy-variable control; effective human review"
    },
    {
        "id": "FR3",
        "risk": "Decision-making opacity and insufficient explanation",
        "rights": "Transparency; effective remedy; defence rights; good administration",
        "triggers": {"actions": ["Scoring/ranking", "Classification", "Recommendation", "Risk prediction", "Exclusion/de-prioritisation"], "decision_effects": ["Legal or similarly significant effect", "Access/exclusion/priority in services or opportunities"]},
        "mechanisms": "Opaque criteria; unexplained score; unclear role of automation; inability to contest",
        "safeguards": "Individual notice; understandable explanation; decision criteria documentation; appeal channel; decision logging"
    },
    {
        "id": "FR4",
        "risk": "Ineffective or merely formal human oversight",
        "rights": "Accountability; effective remedy; due process; good administration",
        "triggers": {"actions": ["Recommendation", "Scoring/ranking", "Risk prediction", "Exclusion/de-prioritisation"], "decision_effects": ["Support to human decision", "Legal or similarly significant effect", "Access/exclusion/priority in services or opportunities"]},
        "mechanisms": "Automation bias; rubber-stamping; lack of override authority; lack of time or competence",
        "safeguards": "Reviewer training; override power; documented review; anti-automation-bias procedure; periodic audit"
    },
    {
        "id": "FR5",
        "risk": "Exclusion from essential goods, services or opportunities",
        "rights": "Access to services; substantive equality; dignity; effective remedy",
        "triggers": {"contexts": ["Employment/HR", "Education", "Credit/insurance", "Welfare/public services", "Healthcare", "Justice/policing/migration"], "actions": ["Exclusion/de-prioritisation", "Scoring/ranking", "Classification"], "decision_effects": ["Access/exclusion/priority in services or opportunities", "Legal or similarly significant effect"]},
        "mechanisms": "Denial of access; de-prioritisation; loss of opportunity; irreversible or time-sensitive harm",
        "safeguards": "Alternative channel; urgent review; human fallback; outcome notification; remedy procedure"
    },
    {
        "id": "FR6",
        "risk": "Disproportionate surveillance and chilling effect",
        "rights": "Privacy; personal liberty; freedom of expression; freedom of association; dignity",
        "triggers": {"actions": ["Monitoring/surveillance", "Identity verification/biometrics", "Content moderation/ranking"], "data_categories": ["Biometric data", "Behavioural data", "Data from multiple sources", "Inferred/profiling data"]},
        "mechanisms": "Continuous observation; behavioural adaptation; excessive identification; function creep",
        "safeguards": "Temporal limits; purpose limitation; reduced granularity; enhanced transparency; monitoring audit"
    },
    {
        "id": "FR7",
        "risk": "Dignity, autonomy and stigmatisation",
        "rights": "Dignity; autonomy; reputation; free development of personality",
        "triggers": {"actions": ["Risk prediction", "Scoring/ranking", "Classification", "Monitoring/surveillance"], "data_categories": ["Inferred/profiling data", "Behavioural data", "Biometric data"]},
        "mechanisms": "Reduction of the person to a score; stigmatising labels; predictive categorisation; loss of self-determination",
        "safeguards": "Limit categories; avoid stigmatising labels; individual explanation; profile correction; qualified human review"
    },
    {
        "id": "FR8",
        "risk": "Freedom of expression, information and pluralism",
        "rights": "Freedom of expression; freedom of information; pluralism; contestability",
        "triggers": {"contexts": ["Platforms/content"], "actions": ["Content moderation/ranking", "Recommendation", "Exclusion/de-prioritisation", "Content generation"]},
        "mechanisms": "Over-removal; under-removal; opacity of ranking; distortion of visibility; chilling effect",
        "safeguards": "Transparent ranking/moderation criteria; user notice; appeal; audit of over-removal and under-removal"
    },
    {
        "id": "FR9",
        "risk": "Accountability gap and unclear allocation of responsibilities",
        "rights": "Accountability; effective remedy; effective protection of rights",
        "triggers": {"actions": ["Scoring/ranking", "Classification", "Recommendation", "Risk prediction", "Content generation", "Other"]},
        "mechanisms": "Unclear role allocation; responsibility shifting; no internal owner; fragmented provider-deployer-controller responsibilities",
        "safeguards": "Accountability matrix; internal owners; logging; audit trail; escalation procedure"
    },
    {
        "id": "FR10",
        "risk": "Ineffective remedy or impossibility of contestation",
        "rights": "Effective remedy; due process; defence rights; good administration",
        "triggers": {"actions": ["Scoring/ranking", "Classification", "Exclusion/de-prioritisation", "Risk prediction", "Content moderation/ranking"], "decision_effects": ["Legal or similarly significant effect", "Access/exclusion/priority in services or opportunities"]},
        "mechanisms": "No complaint channel; complaint without effect; no human review; no reasons given; excessive burden",
        "safeguards": "Complaint mechanism; human channel; response deadlines; reasoned outcome; possibility of review"
    },
    {
        "id": "FR11",
        "risk": "Health or safety harm with fundamental-rights implications",
        "rights": "Right to life; physical and mental integrity; health protection; dignity; non-discrimination",
        "triggers": {"contexts": ["Healthcare", "Physical security/access", "Justice/policing/migration", "Employment/HR", "Welfare/public services"]},
        "mechanisms": "Unsafe output; incorrect risk classification; delayed intervention; false positives or negatives; unequal exposure to harm",
        "safeguards": "Safety testing; emergency fallback; incident escalation; human override; adverse-event monitoring"
    }
]


# ---------------------------------------------------------------------
# UTILITY FUNCTIONS
# ---------------------------------------------------------------------

def has_intersection(values, triggers):
    return bool(set(values).intersection(set(triggers)))


def is_missing_text(value):
    return value is None or str(value).strip() == ""


def no_measure_selected(measures):
    return len(measures) == 0 or "None / to be defined" in measures


def is_provider_role(inputs):
    return "Provider" in inputs["filer_role"] or "Joint assessment team" in inputs["filer_role"]


def is_deployer_role(inputs):
    return "Deployer" in inputs["filer_role"] or "Joint assessment team" in inputs["filer_role"]


def is_info_gap_value(value):
    return value in ["Not known to this filer", "Information to be requested", "To be verified"]


def status_from_audit(audit_rows, fail_threshold=2, partial_threshold=1):
    failed = [row for row in audit_rows if row["Result"] == "Failed"]
    partial = [row for row in audit_rows if row["Result"] == "Partly / to be verified"]
    gaps = [row for row in audit_rows if row["Result"] == "Information gap"]

    if len(failed) >= fail_threshold:
        return "Not demonstrated"
    if failed or len(partial) >= partial_threshold or gaps:
        return "Partially demonstrated"
    return "Demonstrated"


def audit_result(condition, partial=False, info_gap=False):
    if info_gap:
        return "Information gap"
    if condition:
        return "Passed"
    if partial:
        return "Partly / to be verified"
    return "Failed"


# ---------------------------------------------------------------------
# PHASE 0: AI ACT SCOPING
# ---------------------------------------------------------------------

def compute_ai_scoping(inputs):
    audit = []

    audit.append({
        "Criterion": "Machine-based system",
        "Result": audit_result(inputs["ai_machine_based"] == "Yes", inputs["ai_machine_based"] in ["Partly", "To be verified"]),
        "Evidence": inputs["ai_machine_based"]
    })
    audit.append({
        "Criterion": "Some degree of autonomy",
        "Result": audit_result(inputs["ai_autonomy"] == "Yes", inputs["ai_autonomy"] in ["Partly", "To be verified"]),
        "Evidence": inputs["ai_autonomy"]
    })
    audit.append({
        "Criterion": "Inference from inputs",
        "Result": audit_result(inputs["ai_inference"] == "Yes", inputs["ai_inference"] in ["Partly", "To be verified"]),
        "Evidence": inputs["ai_inference"]
    })
    audit.append({
        "Criterion": "Outputs such as predictions, content, recommendations, scores or decisions",
        "Result": audit_result(inputs["ai_outputs"] == "Yes", inputs["ai_outputs"] in ["Partly", "To be verified"]),
        "Evidence": inputs["ai_outputs"]
    })
    audit.append({
        "Criterion": "Output can influence physical or virtual environments",
        "Result": audit_result(inputs["ai_environment_influence"] == "Yes", inputs["ai_environment_influence"] in ["Partly", "To be verified"]),
        "Evidence": inputs["ai_environment_influence"]
    })
    audit.append({
        "Criterion": "Not merely basic data processing, static dashboard, predefined rule execution or simple statistical calculation",
        "Result": audit_result(inputs["ai_not_basic_processing"] == "Yes", inputs["ai_not_basic_processing"] in ["Partly", "To be verified"]),
        "Evidence": inputs["ai_not_basic_processing"]
    })

    passed = sum(1 for row in audit if row["Result"] == "Passed")
    failed = sum(1 for row in audit if row["Result"] == "Failed")
    uncertain = sum(1 for row in audit if row["Result"] == "Partly / to be verified")

    if passed >= 5 and inputs["ai_inference"] == "Yes":
        ai_status = "Likely AI system"
    elif failed >= 3 or inputs["ai_inference"] == "No":
        ai_status = "Likely not an AI system"
    else:
        ai_status = "Borderline / requires legal-technical review"

    gpai_model_signals = [
        inputs["gpai_underlying_model"] == "Yes",
        inputs["gpai_general_tasks"] == "Yes",
        inputs["gpai_downstream_integration"] == "Yes"
    ]

    if all(gpai_model_signals):
        gpai_status = "GPAI model"
    elif inputs["gpai_system_based"] == "Yes":
        gpai_status = "AI system based on a GPAI model"
    elif inputs["gpai_underlying_model"] in ["To be verified", "Partly"] or inputs["gpai_system_based"] in ["To be verified", "Partly"]:
        gpai_status = "GPAI status unclear"
    else:
        gpai_status = "Not GPAI / not based on GPAI"

    high_risk_contexts = {
        "Employment/HR",
        "Education",
        "Credit/insurance",
        "Welfare/public services",
        "Healthcare",
        "Justice/policing/migration",
        "Physical security/access"
    }
    high_risk_actions = {
        "Scoring/ranking",
        "Classification",
        "Exclusion/de-prioritisation",
        "Risk prediction",
        "Identity verification/biometrics"
    }
    significant_effect = inputs["decision_effect"] in [
        "Legal or similarly significant effect",
        "Access/exclusion/priority in services or opportunities"
    ]

    if has_intersection(inputs["contexts"], high_risk_contexts) and (has_intersection(inputs["actions"], high_risk_actions) or significant_effect):
        high_risk_status = "Potentially high-risk AI system"
    elif ai_status == "Likely AI system" and (has_intersection(inputs["contexts"], high_risk_contexts) or significant_effect):
        high_risk_status = "Requires high-risk classification review"
    else:
        high_risk_status = "Not evidently high-risk"

    return {
        "ai_status": ai_status,
        "gpai_status": gpai_status,
        "high_risk_status": high_risk_status,
        "audit": audit,
        "uncertain_items": uncertain
    }


def should_open_provider_module(inputs, scoping):
    if not is_provider_role(inputs):
        return False
    if scoping["ai_status"] == "Likely not an AI system":
        return False
    return scoping["high_risk_status"] in ["Potentially high-risk AI system", "Requires high-risk classification review"]


def should_open_deployer_module(inputs, scoping):
    if not is_deployer_role(inputs):
        return False
    if scoping["ai_status"] == "Likely not an AI system":
        return False
    return scoping["high_risk_status"] in ["Potentially high-risk AI system", "Requires high-risk classification review"]


# ---------------------------------------------------------------------
# DPIA COMPLETENESS, NECESSITY, PROPORTIONALITY
# ---------------------------------------------------------------------

def compute_dpia_completeness(inputs):
    checks = [
        ("Purpose described", not is_missing_text(inputs["purpose"])),
        ("Processing operation described", not is_missing_text(inputs["processing_description"])),
        ("Operational context described", not is_missing_text(inputs["processing_context"])),
        ("Legal basis identified", inputs["legal_basis"] not in ["To be determined", "Not applicable / to be verified"]),
        ("Purpose specificity assessed", inputs["purpose_specificity"] == "Yes"),
        ("Legal basis adequacy assessed", inputs["legal_basis_adequacy"] == "Yes"),
        ("Data categories selected", len(inputs["data_categories"]) > 0),
        ("Data sources selected", len(inputs["data_sources"]) > 0),
        ("Data minimisation assessed", inputs["data_minimisation"] == "Yes"),
        ("Retention limits defined", inputs["retention_limits"] == "Yes"),
        ("Data subjects identified", len(inputs["data_subjects"]) > 0),
        ("Vulnerability reasoning provided where needed", inputs["vulnerable_subjects"] != "Yes" or not is_missing_text(inputs["vulnerability_reasoning"])),
        ("Transparency ensured", inputs["transparency_notice"] == "Yes"),
        ("Data-subject rights operationalised", "None / to be defined" not in inputs["data_subject_rights"]),
        ("Less intrusive alternatives assessed", inputs["alternatives_assessed"] == "Yes"),
        ("Necessity reasoning provided", not is_missing_text(inputs["necessity_reasoning"])),
        ("Proportionality reasoning provided", not is_missing_text(inputs["proportionality_reasoning"])),
        ("DPIA risk described", not is_missing_text(inputs["dpia_risk_description"]))
    ]
    completed = sum(1 for _, ok in checks if ok)
    score = round((completed / len(checks)) * 100)
    missing = [name for name, ok in checks if not ok]
    return score, missing


def compute_necessity_judgment(inputs):
    audit = []

    audit.append({"Criterion": "Purpose is specific, explicit and sufficiently determined", "Result": audit_result(inputs["purpose_specificity"] == "Yes", inputs["purpose_specificity"] in ["Partly", "To be verified"]), "Evidence": inputs["purpose_specificity"]})
    audit.append({"Criterion": "Purpose reasoning is documented", "Result": audit_result(not is_missing_text(inputs["purpose"])), "Evidence": "Provided" if not is_missing_text(inputs["purpose"]) else "Missing"})
    audit.append({"Criterion": "Legal basis is identified", "Result": audit_result(inputs["legal_basis"] not in ["To be determined", "Not applicable / to be verified"]), "Evidence": inputs["legal_basis"]})
    audit.append({"Criterion": "Legal basis adequacy is reasoned", "Result": audit_result(inputs["legal_basis_adequacy"] == "Yes" and not is_missing_text(inputs["legal_basis_reasoning"]), inputs["legal_basis_adequacy"] in ["Partly", "To be verified"]), "Evidence": inputs["legal_basis_adequacy"]})
    audit.append({"Criterion": "Processing operation is described", "Result": audit_result(not is_missing_text(inputs["processing_description"])), "Evidence": "Provided" if not is_missing_text(inputs["processing_description"]) else "Missing"})
    audit.append({"Criterion": "Data are strictly necessary for the purpose", "Result": audit_result(inputs["data_necessary"] == "Yes", inputs["data_necessary"] in ["Partly", "To be verified"]), "Evidence": inputs["data_necessary"]})
    audit.append({"Criterion": "Data minimisation is demonstrated", "Result": audit_result(inputs["data_minimisation"] == "Yes" and not is_missing_text(inputs["data_minimisation_reasoning"]), inputs["data_minimisation"] in ["Partly", "To be verified"]), "Evidence": inputs["data_minimisation"]})
    audit.append({"Criterion": "Less intrusive alternatives were identified and assessed", "Result": audit_result(inputs["alternatives_assessed"] == "Yes", inputs["alternatives_assessed"] in ["Partly", "To be verified"]), "Evidence": inputs["alternatives_assessed"]})
    audit.append({"Criterion": "Necessity reasoning explains why this measure, these data and this degree of automation are required", "Result": audit_result(not is_missing_text(inputs["necessity_reasoning"])), "Evidence": "Provided" if not is_missing_text(inputs["necessity_reasoning"]) else "Missing"})

    status = status_from_audit(audit, fail_threshold=2)
    failed = [row["Criterion"] for row in audit if row["Result"] == "Failed"]
    partial = [row["Criterion"] for row in audit if row["Result"] == "Partly / to be verified"]

    if status == "Demonstrated":
        explanation = "Necessity is demonstrated on the basis of a specific purpose, identified legal basis, strict data necessity, minimisation and assessment of less intrusive alternatives."
    elif status == "Partially demonstrated":
        explanation = "Necessity is only partially demonstrated. Additional reasoning or evidence is needed before the DPIA can be closed."
    else:
        explanation = "Necessity is not demonstrated. The processing should be redesigned or cannot proceed until the failed criteria are addressed."

    return {"status": status, "audit": audit, "failed": failed, "partial": partial, "explanation": explanation}


def compute_proportionality_judgment(inputs, risks, scoping):
    significant_decision = inputs["decision_effect"] in [
        "Legal or similarly significant effect",
        "Access/exclusion/priority in services or opportunities"
    ]
    vulnerable_context = (
        inputs["vulnerable_subjects"] == "Yes"
        or inputs["power_asymmetry"] == "Yes"
        or has_intersection(inputs["groups"], ["Children", "Migrants/asylum seekers", "Persons with disabilities", "Protected or vulnerable groups", "Welfare beneficiaries", "Patients"])
    )
    high_residual_risk = any([
        inputs["dpia_risk_to_rights"] in ["High", "Very high"],
        inputs["data_quality_residual_risk"] in ["High", "Very high"],
        inputs["human_oversight_residual_risk"] in ["High", "Very high"],
        inputs["contestability_residual_risk"] in ["High", "Very high"]
    ])
    concrete_safeguards = not (
        no_measure_selected(inputs["data_quality_measures"])
        or (significant_decision and no_measure_selected(inputs["human_oversight_measures"]))
        or (significant_decision and no_measure_selected(inputs["contestability_measures"]))
    )
    oversight_ok = (not significant_decision) or inputs["human_oversight"] == "Effective"
    remedy_ok = (not significant_decision) or (inputs["contestability"] == "Yes" and inputs["remedy_effectiveness"] == "Yes")
    data_quality_ok = inputs["data_quality_assessed"] == "Yes" and not no_measure_selected(inputs["data_quality_measures"])
    enhanced_safeguards_ok = (not vulnerable_context) or (concrete_safeguards and remedy_ok and oversight_ok)
    provider_risk_ok = True
    deployer_risk_ok = True

    if should_open_provider_module(inputs, scoping):
        provider_risk_ok = not (
            inputs["provider_health_safety_risk"] in ["High", "Very high"]
            or inputs["provider_fr_risk"] in ["High", "Very high"]
            or inputs["provider_misuse_risk"] in ["High", "Very high"]
        ) or inputs["provider_targeted_measures"] == "Yes"

    if should_open_deployer_module(inputs, scoping):
        deployer_risk_ok = inputs["risk_materialisation_measures"] == "Yes" and inputs["deployer_human_oversight_according_to_instructions"] == "Yes"

    audit = [
        {"Criterion": "Proportionality reasoning is documented as legal balancing, not mere cost-benefit", "Result": audit_result(not is_missing_text(inputs["proportionality_reasoning"])), "Evidence": "Provided" if not is_missing_text(inputs["proportionality_reasoning"]) else "Missing"},
        {"Criterion": "Risks to rights and freedoms are identified", "Result": audit_result(len(risks) > 0 or inputs["dpia_risk_to_rights"] in ["Low", "Medium", "High", "Very high"]), "Evidence": f"{len(risks)} risks selected"},
        {"Criterion": "Residual risk is not high or is justified by concrete safeguards", "Result": audit_result(not high_residual_risk or concrete_safeguards, high_residual_risk and concrete_safeguards), "Evidence": f"DPIA: {inputs['dpia_risk_to_rights']}; data quality: {inputs['data_quality_residual_risk']}; oversight: {inputs['human_oversight_residual_risk']}; contestability: {inputs['contestability_residual_risk']}"},
        {"Criterion": "Data-quality safeguards are concrete and verifiable", "Result": audit_result(data_quality_ok, inputs["data_quality_assessed"] in ["Partly", "To be verified"]), "Evidence": "; ".join(inputs["data_quality_measures"])},
        {"Criterion": "Human oversight is effective where the decision may affect persons or opportunities", "Result": audit_result(oversight_ok, inputs["human_oversight"] == "To be verified"), "Evidence": inputs["human_oversight"]},
        {"Criterion": "Contestability and remedy are effective where the decision may affect persons or opportunities", "Result": audit_result(remedy_ok, inputs["contestability"] in ["Partly", "To be verified"] or inputs["remedy_effectiveness"] in ["Partly", "To be verified"]), "Evidence": f"Contestability: {inputs['contestability']}; remedy: {inputs['remedy_effectiveness']}"},
        {"Criterion": "Vulnerable groups or power asymmetries are addressed through enhanced safeguards", "Result": audit_result(enhanced_safeguards_ok, vulnerable_context and concrete_safeguards), "Evidence": "Vulnerable/power-asymmetry context" if vulnerable_context else "Not triggered"},
        {"Criterion": "Provider-side Article 9 risks are addressed where the provider module is triggered", "Result": audit_result(provider_risk_ok, False, should_open_provider_module(inputs, scoping) and is_info_gap_value(inputs["provider_technical_evidence_available"])), "Evidence": inputs["provider_targeted_measures"] if should_open_provider_module(inputs, scoping) else "Not triggered"},
        {"Criterion": "Deployer-side Article 27 safeguards are addressed where the deployer module is triggered", "Result": audit_result(deployer_risk_ok, False, should_open_deployer_module(inputs, scoping) and is_info_gap_value(inputs["deployer_process_evidence_available"])), "Evidence": inputs["risk_materialisation_measures"] if should_open_deployer_module(inputs, scoping) else "Not triggered"}
    ]

    status = status_from_audit(audit, fail_threshold=2)
    failed = [row["Criterion"] for row in audit if row["Result"] == "Failed"]
    partial = [row["Criterion"] for row in audit if row["Result"] in ["Partly / to be verified", "Information gap"]]

    if status == "Demonstrated":
        explanation = "Proportionality is demonstrated because the identified rights interferences are supported by documented balancing, concrete safeguards and acceptable residual risk."
    elif status == "Partially demonstrated":
        explanation = "Proportionality is only partially demonstrated. Additional safeguards, evidence or governance decisions are required before final risk acceptance."
    else:
        explanation = "Proportionality is not demonstrated. The fair balance cannot be verified because risks remain insufficiently mitigated or core safeguards are missing."

    return {"status": status, "audit": audit, "failed": failed, "partial": partial, "explanation": explanation}


# ---------------------------------------------------------------------
# RISK ACTIVATION, INFORMATION GAPS, FLAGS, OUTCOME
# ---------------------------------------------------------------------

def activate_fundamental_rights_risks(inputs, scoping):
    activated = []

    for item in RISK_CATALOG:
        matched = []
        triggers = item["triggers"]
        if "contexts" in triggers and has_intersection(inputs["contexts"], triggers["contexts"]):
            matched.append("deployment context")
        if "actions" in triggers and has_intersection(inputs["actions"], triggers["actions"]):
            matched.append("system action")
        if "data_categories" in triggers and has_intersection(inputs["data_categories"], triggers["data_categories"]):
            matched.append("data category")
        if "decision_effects" in triggers and inputs["decision_effect"] in triggers["decision_effects"]:
            matched.append("effect on persons or opportunities")
        if matched:
            activated.append({
                "Risk ID": item["id"],
                "Fundamental rights risk": item["risk"],
                "Rights involved": item["rights"],
                "Legal mechanisms of harm": item["mechanisms"],
                "Triggered by": ", ".join(matched),
                "Required safeguards to test": item["safeguards"],
                "Risk source": "DPIA-based fundamental-rights layer"
            })

    if should_open_provider_module(inputs, scoping):
        if inputs["provider_health_safety_risk"] in ["High", "Very high"]:
            activated.append({
                "Risk ID": "FR-A9-HS",
                "Fundamental rights risk": "Health and safety risk with spill-over effects on fundamental rights",
                "Rights involved": "Health protection; physical and mental integrity; dignity; equality",
                "Legal mechanisms of harm": "Unsafe output; delayed correction; unequal exposure to harmful consequences",
                "Triggered by": "Article 9 provider-side health/safety risk estimation",
                "Required safeguards to test": "Targeted risk-control measures; safety testing; incident escalation; human override; post-market monitoring",
                "Risk source": "Role-triggered Article 9 AI Act module"
            })
        if inputs["provider_fr_risk"] in ["High", "Very high"]:
            activated.append({
                "Risk ID": "FR-A9-FR",
                "Fundamental rights risk": "Provider-identified fundamental-rights risk insufficiently controlled by design or lifecycle measures",
                "Rights involved": "Privacy; non-discrimination; dignity; remedy; accountability",
                "Legal mechanisms of harm": "Design-level risk; insufficient risk-control measures; lack of lifecycle updating",
                "Triggered by": "Article 9 provider-side fundamental-rights risk estimation",
                "Required safeguards to test": "Risk-management measures; lifecycle update; documentation; post-market feedback; residual-risk definition",
                "Risk source": "Role-triggered Article 9 AI Act module"
            })
        if inputs["provider_misuse_risk"] in ["High", "Very high"]:
            activated.append({
                "Risk ID": "FR-A9-MISUSE",
                "Fundamental rights risk": "Reasonably foreseeable misuse creating fundamental-rights harm",
                "Rights involved": "Privacy; non-discrimination; dignity; effective remedy; accountability",
                "Legal mechanisms of harm": "Use outside intended purpose; over-reliance; function creep; foreseeable organisational misuse",
                "Triggered by": "Article 9 provider-side misuse risk estimation",
                "Required safeguards to test": "Use restrictions; instructions for use; technical guardrails; logging; user training; escalation duties",
                "Risk source": "Role-triggered Article 9 AI Act module"
            })

    if should_open_deployer_module(inputs, scoping):
        if inputs["deployment_frequency"] in ["Regular", "Continuous"]:
            activated.append({
                "Risk ID": "FR-A27-SCALE",
                "Fundamental rights risk": "Repeated or continuous deployment increasing cumulative rights impact",
                "Rights involved": "Privacy; equality; dignity; effective remedy; access to services",
                "Legal mechanisms of harm": "Cumulative exposure; systemic exclusion; repeated surveillance or classification",
                "Triggered by": "Article 27 deployer-side frequency and period of use",
                "Required safeguards to test": "Periodic review; cumulative-impact monitoring; complaint analysis; sampling of decisions; suspension trigger",
                "Risk source": "Role-triggered Article 27 AI Act module"
            })
        if inputs["risk_materialisation_measures"] in ["No", "To be verified"]:
            activated.append({
                "Risk ID": "FR-A27-MATERIALISATION",
                "Fundamental rights risk": "Insufficient measures if rights-related harm materialises",
                "Rights involved": "Effective remedy; accountability; due process; good administration",
                "Legal mechanisms of harm": "No escalation; no complaint handling; delayed correction; lack of remedial pathway",
                "Triggered by": "Article 27 deployer-side risk-materialisation measures",
                "Required safeguards to test": "Incident response; complaint mechanism; governance owner; remedial deadlines; suspension or rollback procedure",
                "Risk source": "Role-triggered Article 27 AI Act module"
            })

    return activated


def compute_information_gaps(inputs, risks, scoping):
    gaps = []

    def add_gap(source, gap, effect, action, owner):
        gaps.append({
            "Source": source,
            "Information gap": gap,
            "Effect on assessment": effect,
            "Required action": action,
            "Suggested owner": owner
        })

    if scoping["ai_status"] == "Borderline / requires legal-technical review":
        add_gap("Phase 0 AI Act scoping", "AI-system qualification is uncertain", "AI Act module triggers and regulatory classification cannot be verified", "Obtain legal-technical assessment of autonomy, inference, outputs and functionality", "Legal team / technical owner")

    if scoping["gpai_status"] == "GPAI status unclear":
        add_gap("Phase 0 AI Act scoping", "GPAI/model/system distinction is unclear", "The assessment may confuse model-level and system-level obligations", "Clarify whether the object is a GPAI model, an AI system based on a GPAI model, or another AI system", "Provider / technical owner")

    if inputs["technical_documentation_available"] in ["Not known to this filer", "Information to be requested", "To be verified"]:
        add_gap("Technical evidence", "Technical documentation is not available to this filer", "Data quality, model limitations and residual risk may not be auditable", "Request technical documentation, limitations, validation evidence and instructions for use", "Provider / technical team")

    if inputs["data_quality_evidence_available"] in ["Not known to this filer", "Information to be requested", "To be verified"]:
        add_gap("Data quality evidence", "Data quality evidence is missing or unavailable", "Necessity and proportionality cannot be fully verified where data quality is a safeguard", "Request data governance documentation, representativeness evidence, bias/proxy testing or validation report", "DPO / data governance lead / provider")

    if "FR2" in [risk["Risk ID"] for risk in risks] and inputs["bias_control"] in ["To be verified", "Partly"]:
        add_gap("Discrimination risk", "Bias or proxy-discrimination safeguards are not fully evidenced", "Residual equality risk remains open", "Request subgroup analysis, proxy-variable review and mitigation evidence", "AI governance / model validation team")

    if should_open_provider_module(inputs, scoping) and inputs["provider_technical_evidence_available"] in ["Not known to this filer", "Information to be requested", "To be verified"]:
        add_gap("Article 9 provider module", "Provider-side risk-management evidence is missing or unavailable", "Provider-side Article 9 outputs cannot fully inform the integrated DPIA reasoning", "Request risk-management documentation, foreseeable misuse analysis, post-market monitoring feedback and residual-risk definition", "Provider")

    if should_open_deployer_module(inputs, scoping) and inputs["deployer_process_evidence_available"] in ["Not known to this filer", "Information to be requested", "To be verified"]:
        add_gap("Article 27 deployer module", "Deployment-process evidence is missing or unavailable", "Article 27 contextual assessment cannot fully inform proportionality and safeguards", "Request process description, affected-person categories, human oversight procedure, complaint mechanism and measures if risks materialise", "Deployer / business process owner")

    if inputs["affected_groups_consulted"] in ["To be verified", "Partly"]:
        add_gap("Participation", "Affected groups or representatives have not been sufficiently consulted", "The proportionality and fair-balancing assessment lacks affected-person perspective", "Document whether consultation is appropriate and, if so, how it will be conducted", "DPO / legal team / business owner")

    return gaps


def compute_red_flags(inputs, risks, scoping, necessity, proportionality, information_gaps):
    flags = []
    risk_ids = {risk["Risk ID"] for risk in risks}
    significant_decision = inputs["decision_effect"] in ["Legal or similarly significant effect", "Access/exclusion/priority in services or opportunities"]

    if necessity["status"] == "Not demonstrated":
        flags.append(("BLOCKING", "Necessity is not demonstrated. The DPIA cannot be closed without redesign or additional justification."))
    elif necessity["status"] == "Partially demonstrated":
        flags.append(("HIGH", "Necessity is only partially demonstrated. Additional justification or evidence is required."))

    if proportionality["status"] == "Not demonstrated":
        flags.append(("BLOCKING", "Proportionality is not demonstrated. The fair balance cannot be verified because risks or safeguards are insufficiently addressed."))
    elif proportionality["status"] == "Partially demonstrated":
        flags.append(("HIGH", "Proportionality is only partially demonstrated. Additional safeguards, evidence or governance decisions are required."))

    if scoping["ai_status"] == "Borderline / requires legal-technical review":
        flags.append(("HIGH", "Phase 0: AI-system qualification is borderline and requires legal-technical review."))

    if scoping["high_risk_status"] == "Requires high-risk classification review":
        flags.append(("HIGH", "Phase 0: high-risk AI classification requires review before role-triggered obligations can be confirmed."))

    if inputs["purpose_compatibility"] in ["No", "To be verified"]:
        flags.append(("HIGH", "DPIA core: purpose compatibility or further-processing compatibility is not sufficiently assessed."))

    if inputs["retention_limits"] in ["No", "To be verified"]:
        flags.append(("MEDIUM", "DPIA core: storage limitation and deletion periods are not clearly defined."))

    if inputs["vulnerable_subjects"] == "Yes" and is_missing_text(inputs["vulnerability_reasoning"]):
        flags.append(("HIGH", "DPIA core: vulnerable persons or groups are involved but vulnerability reasoning is missing."))

    if inputs["power_asymmetry"] == "Yes" and is_missing_text(inputs["vulnerability_reasoning"]):
        flags.append(("HIGH", "DPIA core: power asymmetry is present but not explained."))

    if inputs["transparency_notice"] in ["No", "To be verified"]:
        flags.append(("HIGH", "DPIA core: transparency towards affected persons is not sufficiently ensured."))

    if "None / to be defined" in inputs["data_subject_rights"]:
        flags.append(("HIGH", "DPIA core: data-subject rights are not operationally supported."))

    if inputs["dpia_high_risk"] == "Yes":
        flags.append(("HIGH", "DPIA core: processing remains likely to result in high risk after initial safeguards."))

    if no_measure_selected(inputs["data_quality_measures"]):
        flags.append(("HIGH", "Mitigation layer: data quality measures are missing or still to be defined."))

    if "FR2" in risk_ids and inputs["bias_control"] in ["No", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: discrimination risk is present, but bias/proxy-control safeguards are not sufficiently demonstrated."))

    if significant_decision and inputs["human_oversight"] in ["Absent", "Merely formal", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: human oversight is absent, merely formal or insufficiently demonstrated in a significant decision-making context."))

    if significant_decision and no_measure_selected(inputs["human_oversight_measures"]):
        flags.append(("HIGH", "Mitigation layer: human oversight measures are missing or still to be defined in a significant decision-making context."))

    if significant_decision and inputs["contestability"] != "Yes":
        flags.append(("BLOCKING", "Mitigation layer: affected persons cannot effectively contest a significant outcome."))

    if significant_decision and inputs["remedy_effectiveness"] in ["No", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: the remedy is not shown to be capable of changing the outcome."))

    if significant_decision and no_measure_selected(inputs["contestability_measures"]):
        flags.append(("BLOCKING", "Mitigation layer: contestability measures are missing or still to be defined in a significant decision-making context."))

    if "FR5" in risk_ids and inputs["fallback_channel"] in ["No", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: potential exclusion from services or opportunities is present without a reliable fallback channel."))

    if should_open_provider_module(inputs, scoping):
        if inputs["provider_lifecycle_review"] in ["No", "To be verified"]:
            flags.append(("MEDIUM", "Article 9 provider module: lifecycle review and updating are not clearly established."))
        if inputs["provider_health_safety_risk"] in ["High", "Very high"] and inputs["provider_targeted_measures"] != "Yes":
            flags.append(("HIGH", "Article 9 provider module: high health/safety risk without targeted risk-management measures."))
        if inputs["provider_fr_risk"] in ["High", "Very high"] and inputs["provider_targeted_measures"] != "Yes":
            flags.append(("HIGH", "Article 9 provider module: high fundamental-rights risk without targeted risk-management measures."))
        if inputs["provider_misuse_risk"] in ["High", "Very high"] and inputs["misuse_assessed"] != "Yes":
            flags.append(("HIGH", "Article 9 provider module: high misuse risk is not sufficiently assessed."))

    if should_open_deployer_module(inputs, scoping):
        if is_missing_text(inputs["deployer_process_description"]):
            flags.append(("HIGH", "Article 27 deployer module: the deployer's process in which the AI system will be used is not described."))
        if inputs["affected_categories_described"] != "Yes":
            flags.append(("HIGH", "Article 27 deployer module: affected persons and groups are not sufficiently described."))
        if inputs["provider_article13_info_used"] in ["No", "To be verified"]:
            flags.append(("MEDIUM", "Article 27 deployer module: provider information or instructions have not been used or verified."))
        if inputs["deployer_human_oversight_according_to_instructions"] in ["No", "To be verified"]:
            flags.append(("HIGH", "Article 27 deployer module: human oversight according to provider instructions is not demonstrated."))
        if inputs["risk_materialisation_measures"] in ["No", "To be verified"]:
            flags.append(("HIGH", "Article 27 deployer module: measures in case risks materialise are missing or insufficient."))

    if len(information_gaps) >= 4:
        flags.append(("HIGH", "Information gaps: multiple missing information items affect the auditability of the assessment."))

    return flags


def compute_scrutiny_level(inputs, flags, risks, necessity, proportionality, information_gaps):
    score = 0
    high_contexts = {"Employment/HR", "Education", "Credit/insurance", "Welfare/public services", "Healthcare"}
    very_high_contexts = {"Justice/policing/migration"}
    vulnerable_groups = {"Children", "Migrants/asylum seekers", "Persons with disabilities", "Protected or vulnerable groups", "Welfare beneficiaries", "Patients"}
    sensitive_data = {"Special categories of data", "Biometric data", "Children's data"}

    if has_intersection(inputs["contexts"], high_contexts):
        score += 2
    if has_intersection(inputs["contexts"], very_high_contexts):
        score += 3
    if has_intersection(inputs["groups"], vulnerable_groups):
        score += 3
    if has_intersection(inputs["data_categories"], sensitive_data):
        score += 3
    if inputs["decision_effect"] in ["Legal or similarly significant effect", "Access/exclusion/priority in services or opportunities"]:
        score += 3
    if inputs["dpia_risk_to_rights"] in ["High", "Very high"] or inputs["dpia_high_risk"] == "Yes":
        score += 3
    if inputs["vulnerable_subjects"] == "Yes":
        score += 2
    if inputs["power_asymmetry"] == "Yes":
        score += 2
    if len(risks) >= 5:
        score += 2
    if any(level == "BLOCKING" for level, _ in flags):
        score += 4
    if necessity["status"] == "Not demonstrated" or proportionality["status"] == "Not demonstrated":
        score += 4
    if information_gaps:
        score += min(len(information_gaps), 3)

    if score >= 11:
        return "Very high"
    if score >= 7:
        return "High"
    if score >= 3:
        return "Medium"
    return "Low"


def compute_outcome(flags, necessity, proportionality, information_gaps):
    if necessity["status"] == "Not demonstrated":
        return "NO-GO / redesign required: necessity is not demonstrated"
    if proportionality["status"] == "Not demonstrated":
        return "NO-GO / redesign required: proportionality is not demonstrated"
    if any(level == "BLOCKING" for level, _ in flags):
        return "NO-GO / redesign required before deployment"
    if len(information_gaps) >= 4:
        return "ESCALATE / DPIA cannot be closed until major information gaps are resolved"
    if necessity["status"] == "Partially demonstrated" or proportionality["status"] == "Partially demonstrated":
        return "CONDITIONAL GO / additional evidence, safeguards or reasoning required"
    if any(level == "HIGH" for level, _ in flags):
        return "CONDITIONAL GO with mandatory safeguards and escalation"
    if any(level == "MEDIUM" for level, _ in flags):
        return "GO with documented review and monitoring"
    return "GO"


# ---------------------------------------------------------------------
# REGISTERS, ACTION PLAN, REPORT
# ---------------------------------------------------------------------

def compute_risk_priority(risk, flags):
    if risk["Risk ID"] in ["FR-A9-HS", "FR-A9-FR", "FR-A9-MISUSE", "FR-A27-MATERIALISATION"]:
        return "High"
    if any(level == "BLOCKING" for level, _ in flags):
        return "High"
    if risk["Risk ID"] in ["FR2", "FR4", "FR5", "FR10", "FR11"]:
        return "High"
    return "Medium"


def build_summary_risk_register(risks, flags):
    return pd.DataFrame([
        {
            "Risk ID": risk["Risk ID"],
            "Priority": compute_risk_priority(risk, flags),
            "Source": risk["Risk source"],
            "Risk": risk["Fundamental rights risk"],
            "Status": "Open"
        }
        for risk in risks
    ])


def build_operational_risk_register(risks, flags):
    return pd.DataFrame([
        {
            "Risk ID": risk["Risk ID"],
            "Risk source": risk["Risk source"],
            "Priority": compute_risk_priority(risk, flags),
            "Fundamental rights risk": risk["Fundamental rights risk"],
            "Rights involved": risk["Rights involved"],
            "Triggered by": risk["Triggered by"],
            "Legal mechanisms of harm": risk["Legal mechanisms of harm"],
            "Required safeguards to test": risk["Required safeguards to test"],
            "Assessment status": "Open"
        }
        for risk in risks
    ])


def suggested_actions_for_risk(risk_id):
    actions = {
        "FR1": [("Review data minimisation and retention", "Data inventory; minimisation memo; retention schedule")],
        "FR2": [("Perform bias and proxy-variable analysis", "Bias testing report; subgroup performance analysis")],
        "FR3": [("Prepare meaningful explanation of outcome", "Explanation template; decision criteria documentation")],
        "FR4": [("Strengthen human oversight", "Human oversight procedure; override protocol; reviewer training")],
        "FR5": [("Create fallback or alternative access channel", "Fallback procedure; escalation workflow")],
        "FR6": [("Limit monitoring scope and duration", "Monitoring policy; purpose limitation statement")],
        "FR7": [("Review profiling and labelling logic", "Profile taxonomy; label-risk review")],
        "FR8": [("Audit ranking or moderation effects", "Moderation/ranking audit; appeal workflow")],
        "FR9": [("Create accountability matrix", "RACI matrix; escalation and audit-trail procedure")],
        "FR10": [("Create accessible complaint mechanism", "Complaint workflow; human review and reversal powers")],
        "FR11": [("Perform safety and adverse-event testing", "Safety testing report; incident response plan")],
        "FR-A9-HS": [("Adopt targeted health/safety risk-control measures", "Safety risk register; targeted mitigation plan")],
        "FR-A9-FR": [("Link Article 9 risk controls to fundamental-rights safeguards", "Risk-management file; lifecycle review evidence")],
        "FR-A9-MISUSE": [("Assess and document foreseeable misuse scenarios", "Misuse analysis; use restrictions; instructions for use")],
        "FR-A27-SCALE": [("Monitor cumulative impact of repeated deployment", "Periodic review report; complaint trend analysis")],
        "FR-A27-MATERIALISATION": [("Define measures if risks materialise", "Incident response plan; complaint escalation workflow")]
    }
    return actions.get(risk_id, [("Perform manual legal review", "Legal assessment note; governance decision")])


def suggest_owner_for_action(action):
    text = action.lower()
    if "data" in text or "minimisation" in text:
        return "DPO / data governance lead"
    if "bias" in text or "testing" in text:
        return "AI governance / model validation team"
    if "human" in text or "oversight" in text:
        return "Business process owner / human oversight lead"
    if "complaint" in text or "appeal" in text or "remedy" in text:
        return "Legal / complaints handling team"
    if "safety" in text or "incident" in text:
        return "Risk management / safety owner"
    if "accountability" in text or "raci" in text:
        return "AI governance officer"
    return "Assessment owner"


def build_mitigation_action_plan(risks, flags):
    rows = []
    for risk in risks:
        risk_id = risk["Risk ID"]
        priority = compute_risk_priority(risk, flags)
        for action, evidence in suggested_actions_for_risk(risk_id):
            rows.append({
                "Risk ID": risk_id,
                "Priority": priority,
                "Action required": action,
                "Evidence to collect": evidence,
                "Suggested owner": suggest_owner_for_action(action),
                "Status": "To be started",
                "Deadline": "To be defined",
                "Evidence collected": "",
                "Residual risk after action": "To be verified"
            })
    return pd.DataFrame(rows)


def build_report(result, final_decision_log):
    inputs = result["inputs"]
    scoping = result["scoping"]
    risks = result["risks"]
    flags = result["flags"]
    necessity = result["necessity"]
    proportionality = result["proportionality"]
    information_gaps = result["information_gaps"]

    lines = []
    lines.append("# DPIA-based Fundamental Rights Assessment Report")
    lines.append("")
    lines.append(f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")
    lines.append("## Methodological note")
    lines.append("This tool uses the DPIA as the common methodological backbone. Where the filer acts as provider, the Article 9 AI Act risk-management module is opened. Where the filer acts as deployer, the Article 27 AI Act fundamental-rights impact assessment module is opened. These remain distinct legal obligations, but their outputs are integrated into the DPIA-based reasoning on risks, safeguards, necessity, proportionality, accountability and contestability.")
    lines.append("")
    lines.append("## 0. AI Act scoping")
    lines.append(f"- AI-system status: {scoping['ai_status']}")
    lines.append(f"- GPAI status: {scoping['gpai_status']}")
    lines.append(f"- High-risk relevance: {scoping['high_risk_status']}")
    lines.append("")
    lines.append("## 1. Assessment scope")
    lines.append(f"- Project name: {inputs['project_name']}")
    lines.append(f"- Organisation: {inputs['organisation']}")
    lines.append(f"- Filer role: {', '.join(inputs['filer_role'])}")
    lines.append(f"- Accountability owner: {inputs['accountability_owner']}")
    lines.append("")
    lines.append("## 2. DPIA core")
    lines.append(f"- DPIA completeness: {result['dpia_score']}%")
    lines.append(f"- Purpose: {inputs['purpose']}")
    lines.append(f"- Legal basis: {inputs['legal_basis']}")
    lines.append(f"- Data categories: {', '.join(inputs['data_categories'])}")
    lines.append(f"- Data subjects: {', '.join(inputs['data_subjects'])}")
    lines.append(f"- DPIA baseline risk: {inputs['dpia_risk_to_rights']}")
    lines.append("")
    lines.append("## 3. Necessity judgment")
    lines.append(f"- Judgment: {necessity['status']}")
    lines.append(f"- Explanation: {necessity['explanation']}")
    for row in necessity["audit"]:
        lines.append(f"  - {row['Criterion']}: {row['Result']} ({row['Evidence']})")
    lines.append("")
    lines.append("## 4. Proportionality judgment")
    lines.append(f"- Judgment: {proportionality['status']}")
    lines.append(f"- Explanation: {proportionality['explanation']}")
    for row in proportionality["audit"]:
        lines.append(f"  - {row['Criterion']}: {row['Result']} ({row['Evidence']})")
    lines.append("")
    lines.append("## 5. Role-triggered AI Act modules")
    lines.append(f"- Article 9 provider module opened: {should_open_provider_module(inputs, scoping)}")
    lines.append(f"- Article 27 deployer module opened: {should_open_deployer_module(inputs, scoping)}")
    lines.append("")
    lines.append("## 6. Information gaps")
    if information_gaps:
        for gap in information_gaps:
            lines.append(f"- {gap['Source']}: {gap['Information gap']} | action: {gap['Required action']}")
    else:
        lines.append("No information gaps detected.")
    lines.append("")
    lines.append("## 7. Risks and red flags")
    lines.append(f"- Fundamental-rights risks selected: {len(risks)}")
    for risk in risks:
        lines.append(f"  - {risk['Risk ID']}: {risk['Fundamental rights risk']} ({risk['Risk source']})")
    if flags:
        for level, message in flags:
            lines.append(f"- [{level}] {message}")
    else:
        lines.append("No red flags detected.")
    lines.append("")
    lines.append("## 8. Outcome")
    lines.append(f"- Scrutiny level: {result['scrutiny_level']}")
    lines.append(f"- Recommended outcome: {result['outcome']}")
    lines.append("")
    lines.append("## 9. Final governance decision log")
    for key, value in final_decision_log.items():
        lines.append(f"- {key}: {value}")
    return "\n".join(lines)


# ---------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------

with st.expander("Methodological logic", expanded=True):
    st.markdown(
        """
        This tool uses the **DPIA as the common methodological backbone**.

        **Article 9 AI Act** and **Article 27 AI Act** remain distinct legal obligations. They are not absorbed by the DPIA. However, in this tool they are opened as **role-triggered modules**:

        - the Article 9 risk-management module opens where the filer acts as **provider** and the AI/high-risk trigger is relevant;
        - the Article 27 fundamental-rights impact assessment module opens where the filer acts as **deployer** and the AI/high-risk trigger is relevant;
        - both modules open for a **joint assessment team** where relevant.

        Their outputs feed the same integrated reasoning on **risks, safeguards, necessity, proportionality, accountability and contestability**.

        Necessity and proportionality are not merely descriptive text fields. They are computed as **auditable legal judgments** based on the DPIA inputs, identified risks, safeguards, residual risks and information gaps.
        """
    )

with st.form("assessment_form"):
    st.header("0. AI Act scoping checklist")
    st.caption("This phase determines the object of assessment: non-AI software, AI system, GPAI model, AI system based on a GPAI model, and potential high-risk relevance. It does not replace the DPIA.")

    col0a, col0b = st.columns(2)
    with col0a:
        ai_machine_based = st.selectbox("Is the tool machine-based?", YES_NO_OPTIONS)
        ai_autonomy = st.selectbox("Does it operate with some degree of autonomy?", YES_NO_OPTIONS)
        ai_inference = st.selectbox("Does it infer outputs from inputs?", YES_NO_OPTIONS)
    with col0b:
        ai_outputs = st.selectbox("Does it generate predictions, recommendations, content, scores, classifications or decisions?", YES_NO_OPTIONS)
        ai_environment_influence = st.selectbox("Can the output influence a physical or virtual environment?", YES_NO_OPTIONS)
        ai_not_basic_processing = st.selectbox("Is it more than basic data processing, a static dashboard, predefined rule execution or simple statistical calculation?", YES_NO_OPTIONS)

    st.subheader("0.2 GPAI / model-system distinction")
    col0c, col0d = st.columns(2)
    with col0c:
        gpai_underlying_model = st.selectbox("Is the object assessed the underlying model itself?", YES_NO_OPTIONS)
        gpai_general_tasks = st.selectbox("Can the model perform a wide range of distinct tasks?", YES_NO_OPTIONS)
    with col0d:
        gpai_downstream_integration = st.selectbox("Can the model be integrated into many downstream systems or applications?", YES_NO_OPTIONS)
        gpai_system_based = st.selectbox("Is the assessed tool a deployable AI system based on a GPAI model?", YES_NO_OPTIONS)

    st.header("1. Assessment scope")
    col1, col2 = st.columns(2)
    with col1:
        project_name = st.text_input("Project name", "Recruitment AI Pilot")
        organisation = st.text_input("Organisation", "Example organisation")
        filer_role = st.multiselect("Who is completing this assessment?", FILER_ROLES, default=["Controller / data protection team"])
    with col2:
        accountability_owner = st.text_input("Accountability owner", "DPO / AI Governance Officer")
        legal_basis = st.selectbox("Legal basis", LEGAL_BASES)
        data_necessary = st.selectbox("Are data strictly necessary for the stated purpose?", YES_NO_OPTIONS)

    st.header("2. DPIA core analysis")
    st.markdown("This is the common methodological backbone of the tool. It must be completed regardless of whether Article 9 or Article 27 modules are opened.")

    st.subheader("2.1 Processing description")
    purpose = st.text_area("Purpose of the processing / AI use", "", placeholder="Describe the specific, explicit and legitimate purpose of the processing and explain how the system contributes to it.")
    processing_description = st.text_area("Systematic description of the processing operation", "", placeholder="Describe data collection, data sources, input data, model/system use, output generation, human decision-making, storage, sharing and deletion.")
    processing_context = st.text_area("Operational and organisational context", "", placeholder="Describe the organisational process, actors involved and practical setting of the decision.")

    st.subheader("2.2 Legal basis, purpose limitation and compatibility")
    col3, col4 = st.columns(2)
    with col3:
        purpose_specificity = st.selectbox("Is the purpose specific, explicit and sufficiently determined?", YES_NO_OPTIONS)
        legal_basis_adequacy = st.selectbox("Is the selected legal basis adequate for this processing operation?", YES_NO_OPTIONS)
        purpose_compatibility = st.selectbox("If data are reused, has compatibility with the original purpose been assessed?", YES_NO_NA_OPTIONS)
    with col4:
        legal_basis_reasoning = st.text_area("Legal basis reasoning", "", placeholder="Explain why the selected legal basis applies, including balancing or public-interest justification where relevant.")
        compatibility_reasoning = st.text_area("Purpose limitation / compatibility reasoning", "", placeholder="Explain compatibility and whether further processing creates additional risks.")

    st.subheader("2.3 Data categories, minimisation and retention")
    data_categories = st.multiselect("Data categories", DATA_CATEGORIES, default=["Common personal data"])
    col5, col6 = st.columns(2)
    with col5:
        data_sources = st.multiselect("Data sources", DATA_SOURCES, default=[])
        data_minimisation = st.selectbox("Are the data limited to what is necessary for the purpose?", YES_NO_OPTIONS)
        retention_limits = st.selectbox("Are storage limitation and deletion periods defined?", YES_NO_OPTIONS)
    with col6:
        data_minimisation_reasoning = st.text_area("Data minimisation reasoning", "", placeholder="Explain why each data category is necessary and whether less data, less granular data or shorter retention would achieve the same purpose.")
        retention_reasoning = st.text_area("Retention reasoning", "", placeholder="Explain retention periods, deletion rules and archiving/logging needs.")

    st.subheader("2.4 Data subjects, vulnerabilities and power asymmetries")
    col7, col8 = st.columns(2)
    with col7:
        data_subjects = st.multiselect("Categories of data subjects", GROUPS, default=["Workers/candidates"])
        vulnerable_subjects = st.selectbox("Are vulnerable persons or groups involved?", YES_NO_OPTIONS)
        power_asymmetry = st.selectbox("Is there a significant power asymmetry between the organisation and affected persons?", YES_NO_OPTIONS)
    with col8:
        vulnerability_reasoning = st.text_area("Vulnerability and power-asymmetry reasoning", "", placeholder="Explain whether affected persons are workers, students, patients, welfare recipients, children, migrants or other persons in a dependent or vulnerable position.")

    st.subheader("2.5 Transparency and data-subject rights")
    col9, col10 = st.columns(2)
    with col9:
        transparency_notice = st.selectbox("Are affected persons informed in a clear and understandable way?", YES_NO_OPTIONS)
        data_subject_rights = st.multiselect("Which data-subject rights are operationally supported?", DATA_SUBJECT_RIGHTS, default=["None / to be defined"])
    with col10:
        rights_exercise_notes = st.text_area("Transparency and rights-exercise notes", "", placeholder="Explain how affected persons are informed and how rights are exercised in practice.")

    st.subheader("2.6 DPIA necessity and proportionality inputs")
    col11, col12 = st.columns(2)
    with col11:
        alternatives_assessed = st.selectbox("Have less intrusive alternatives been assessed?", YES_NO_OPTIONS)
        necessity_reasoning = st.text_area("Necessity reasoning", "", placeholder="Why is this processing necessary? Why this system, these data and this degree of automation? Could the purpose be achieved with a less intrusive measure?")
    with col12:
        proportionality_reasoning = st.text_area("Proportionality reasoning", "", placeholder="Explain the legal balancing of rights and interests. Which benefits justify the interference? Who benefits, who bears the risk, and are safeguards sufficient?")

    st.subheader("2.7 DPIA baseline risk assessment")
    col13, col14 = st.columns(2)
    with col13:
        dpia_risk_to_rights = st.selectbox("Baseline risk to rights and freedoms under the DPIA", RISK_LEVELS)
        dpia_high_risk = st.selectbox("Does the processing remain likely to result in high risk after initial safeguards?", YES_NO_OPTIONS)
    with col14:
        dpia_risk_description = st.text_area("DPIA risk description", "", placeholder="Describe the main risks to rights and freedoms arising from the processing itself.")

    st.header("3. Decision-making and fundamental-rights context")
    col15, col16 = st.columns(2)
    with col15:
        contexts = st.multiselect("Deployment context", CONTEXTS, default=["Employment/HR"])
        actions = st.multiselect("System action", ACTIONS, default=["Scoring/ranking"])
    with col16:
        decision_effect = st.selectbox("Effect on persons, groups or opportunities", DECISION_EFFECTS)
        groups = st.multiselect("Affected persons or groups", GROUPS, default=["Workers/candidates"])

    st.header("4. Mitigation measures: data quality, human oversight and contestability")
    col17, col18 = st.columns(2)
    with col17:
        data_quality_assessed = st.selectbox("Has data quality been assessed?", YES_NO_OPTIONS)
        data_quality_measures = st.multiselect("Which data quality measures are in place?", DATA_QUALITY_MEASURES, default=["None / to be defined"])
        data_quality_residual_risk = st.selectbox("Residual risk after data quality measures", RISK_LEVELS)
        data_quality_evidence_available = st.selectbox("Is data-quality evidence available to this filer?", EVIDENCE_OPTIONS)
    with col18:
        bias_control = st.selectbox("Are bias and proxy-discrimination safeguards demonstrated?", YES_NO_OPTIONS)
        data_governance_notes = st.text_area("Data quality and governance notes", "", placeholder="Explain data sources, representativeness, limitations, bias/proxy controls, error correction and residual risk.")
        technical_documentation_available = st.selectbox("Is technical documentation available to this filer?", EVIDENCE_OPTIONS)

    st.subheader("4.2 Human oversight")
    col19, col20 = st.columns(2)
    with col19:
        human_oversight = st.selectbox("Is there meaningful human oversight?", ["Effective", "Merely formal", "Absent", "Not applicable", "To be verified"])
        human_oversight_measures = st.multiselect("Which human oversight measures are in place?", HUMAN_OVERSIGHT_MEASURES, default=["None / to be defined"])
        human_oversight_residual_risk = st.selectbox("Residual risk after human oversight measures", RISK_LEVELS)
    with col20:
        human_oversight_notes = st.text_area("Human oversight notes", "", placeholder="Explain who reviews the output, when, with what authority, whether they can override it, and how automation bias is prevented.")

    st.subheader("4.3 Contestability, remedy and complaint mechanisms")
    col21, col22 = st.columns(2)
    with col21:
        contestability = st.selectbox("Can affected persons contest the outcome?", YES_NO_OPTIONS)
        remedy_effectiveness = st.selectbox("Is the remedy capable of changing the outcome?", YES_NO_OPTIONS)
        contestability_measures = st.multiselect("Which contestability measures are in place?", CONTESTABILITY_MEASURES, default=["None / to be defined"])
    with col22:
        fallback_channel = st.selectbox("Is there a reliable non-automated or alternative channel where needed?", YES_NO_OPTIONS)
        contestability_residual_risk = st.selectbox("Residual risk after contestability measures", RISK_LEVELS)
        affected_groups_consulted = st.selectbox("Have affected groups or representatives been consulted?", YES_NO_NA_OPTIONS)
    contestability_notes = st.text_area("Contestability and remedy notes", "", placeholder="Explain how affected persons are informed, how they can contest, and how complaints are handled.")

    st.subheader("4.4 Governance of mitigation measures")
    governance_notes = st.text_area("Governance and accountability notes", "", placeholder="Who owns each mitigation measure? Who monitors effectiveness? Who updates the assessment? Who accepts residual risk?")

    provisional_inputs = {
        "filer_role": filer_role,
        "ai_machine_based": ai_machine_based,
        "ai_autonomy": ai_autonomy,
        "ai_inference": ai_inference,
        "ai_outputs": ai_outputs,
        "ai_environment_influence": ai_environment_influence,
        "ai_not_basic_processing": ai_not_basic_processing,
        "gpai_underlying_model": gpai_underlying_model,
        "gpai_general_tasks": gpai_general_tasks,
        "gpai_downstream_integration": gpai_downstream_integration,
        "gpai_system_based": gpai_system_based,
        "contexts": contexts,
        "actions": actions,
        "decision_effect": decision_effect
    }
    provisional_scoping = compute_ai_scoping(provisional_inputs)
    show_provider_module = should_open_provider_module(provisional_inputs, provisional_scoping)
    show_deployer_module = should_open_deployer_module(provisional_inputs, provisional_scoping)

    st.header("5. Role-triggered AI Act modules")
    st.caption("These modules remain distinct obligations. They open only when the role and AI/high-risk scoping make them relevant.")

    if show_provider_module:
        st.subheader("5A. Provider-side Article 9 AI Act risk-management module")
        col23, col24 = st.columns(2)
        with col23:
            provider_lifecycle_review = st.selectbox("Is the risk-management system continuous, iterative and updated across the lifecycle?", YES_NO_OPTIONS)
            provider_health_safety_risk = st.selectbox("Known or reasonably foreseeable risk to health or safety", RISK_LEVELS)
            provider_fr_risk = st.selectbox("Known or reasonably foreseeable risk to fundamental rights", RISK_LEVELS)
            provider_intended_purpose_risk = st.selectbox("Risk when used according to intended purpose", RISK_LEVELS)
        with col24:
            provider_misuse_risk = st.selectbox("Risk under reasonably foreseeable misuse", RISK_LEVELS)
            misuse_assessed = st.selectbox("Has reasonably foreseeable misuse been specifically assessed?", YES_NO_OPTIONS)
            provider_post_market_link = st.selectbox("Are risks from post-market monitoring linked back to risk review?", YES_NO_OPTIONS)
            provider_targeted_measures = st.selectbox("Have appropriate and targeted risk-management measures been adopted?", YES_NO_OPTIONS)
        residual_risk_defined = st.selectbox("Has residual risk been defined and documented?", YES_NO_OPTIONS)
        provider_technical_evidence_available = st.selectbox("Is provider-side technical/risk-management evidence available to this filer?", EVIDENCE_OPTIONS)
        provider_article9_notes = st.text_area("Provider-side Article 9 notes", "", placeholder="Explain health/safety risks, fundamental-rights risks, misuse scenarios, post-market feedback, targeted measures and residual risk.")
    else:
        st.info("Article 9 provider module is not opened because the current role/scoping combination does not trigger it.")
        provider_lifecycle_review = "Not applicable"
        provider_health_safety_risk = "Low"
        provider_fr_risk = "Low"
        provider_intended_purpose_risk = "Low"
        provider_misuse_risk = "Low"
        misuse_assessed = "Not applicable"
        provider_post_market_link = "Not applicable"
        provider_targeted_measures = "Not applicable"
        residual_risk_defined = "Not applicable"
        provider_technical_evidence_available = "Not applicable"
        provider_article9_notes = "Not applicable"

    if show_deployer_module:
        st.subheader("5B. Deployer-side Article 27 AI Act fundamental-rights impact assessment module")
        deployer_process_description = st.text_area("Description of the deployer's process in which the high-risk AI system will be used", "", placeholder="Describe the process, decision flow, human roles and operational setting.")
        col25, col26 = st.columns(2)
        with col25:
            deployment_period = st.text_input("Expected period of use", "To be verified")
            deployment_frequency = st.selectbox("Expected frequency of use", FREQUENCY_OPTIONS)
            affected_categories_described = st.selectbox("Are categories of affected natural persons and groups described?", YES_NO_OPTIONS)
            provider_article13_info_used = st.selectbox("Has provider information/instructions been used for this assessment?", YES_NO_OPTIONS)
        with col26:
            deployer_human_oversight_according_to_instructions = st.selectbox("Is human oversight implemented according to the provider's instructions for use?", YES_NO_OPTIONS)
            risk_materialisation_measures = st.selectbox("Are measures defined for the materialisation of risks?", YES_NO_OPTIONS)
            monitoring = st.selectbox("Is post-deployment monitoring planned?", YES_NO_OPTIONS)
            deployer_process_evidence_available = st.selectbox("Is deployer-side process/governance evidence available to this filer?", EVIDENCE_OPTIONS)
        deployer_specific_harms = st.text_area("Specific risks of harm likely to affect the identified persons or groups", "", placeholder="Describe specific harms in this context, taking into account provider information, affected groups, frequency of use and organisational setting.")
        deployer_governance_complaints = st.text_area("Internal governance and complaint mechanisms", "", placeholder="Describe governance, complaint channels, escalation routes, deadlines, and measures if risks materialise.")
    else:
        st.info("Article 27 deployer module is not opened because the current role/scoping combination does not trigger it.")
        deployer_process_description = "Not applicable"
        deployment_period = "Not applicable"
        deployment_frequency = "Not applicable"
        affected_categories_described = "Not applicable"
        provider_article13_info_used = "Not applicable"
        deployer_human_oversight_according_to_instructions = "Not applicable"
        risk_materialisation_measures = "Not applicable"
        monitoring = "Not applicable"
        deployer_process_evidence_available = "Not applicable"
        deployer_specific_harms = "Not applicable"
        deployer_governance_complaints = "Not applicable"

    submitted = st.form_submit_button("Generate fundamental rights assessment")


if submitted:
    inputs = {
        "ai_machine_based": ai_machine_based,
        "ai_autonomy": ai_autonomy,
        "ai_inference": ai_inference,
        "ai_outputs": ai_outputs,
        "ai_environment_influence": ai_environment_influence,
        "ai_not_basic_processing": ai_not_basic_processing,
        "gpai_underlying_model": gpai_underlying_model,
        "gpai_general_tasks": gpai_general_tasks,
        "gpai_downstream_integration": gpai_downstream_integration,
        "gpai_system_based": gpai_system_based,
        "project_name": project_name,
        "organisation": organisation,
        "filer_role": filer_role,
        "accountability_owner": accountability_owner,
        "legal_basis": legal_basis,
        "data_necessary": data_necessary,
        "purpose": purpose,
        "processing_description": processing_description,
        "processing_context": processing_context,
        "purpose_specificity": purpose_specificity,
        "legal_basis_adequacy": legal_basis_adequacy,
        "purpose_compatibility": purpose_compatibility,
        "legal_basis_reasoning": legal_basis_reasoning,
        "compatibility_reasoning": compatibility_reasoning,
        "data_categories": data_categories,
        "data_sources": data_sources,
        "data_minimisation": data_minimisation,
        "retention_limits": retention_limits,
        "data_minimisation_reasoning": data_minimisation_reasoning,
        "retention_reasoning": retention_reasoning,
        "data_subjects": data_subjects,
        "vulnerable_subjects": vulnerable_subjects,
        "power_asymmetry": power_asymmetry,
        "vulnerability_reasoning": vulnerability_reasoning,
        "transparency_notice": transparency_notice,
        "data_subject_rights": data_subject_rights,
        "rights_exercise_notes": rights_exercise_notes,
        "alternatives_assessed": alternatives_assessed,
        "necessity_reasoning": necessity_reasoning,
        "proportionality_reasoning": proportionality_reasoning,
        "dpia_risk_to_rights": dpia_risk_to_rights,
        "dpia_high_risk": dpia_high_risk,
        "dpia_risk_description": dpia_risk_description,
        "contexts": contexts,
        "actions": actions,
        "decision_effect": decision_effect,
        "groups": groups,
        "data_quality_assessed": data_quality_assessed,
        "data_quality_measures": data_quality_measures,
        "data_quality_residual_risk": data_quality_residual_risk,
        "data_quality_evidence_available": data_quality_evidence_available,
        "data_governance_notes": data_governance_notes,
        "technical_documentation_available": technical_documentation_available,
        "human_oversight": human_oversight,
        "human_oversight_measures": human_oversight_measures,
        "human_oversight_residual_risk": human_oversight_residual_risk,
        "human_oversight_notes": human_oversight_notes,
        "contestability": contestability,
        "remedy_effectiveness": remedy_effectiveness,
        "contestability_measures": contestability_measures,
        "fallback_channel": fallback_channel,
        "contestability_residual_risk": contestability_residual_risk,
        "affected_groups_consulted": affected_groups_consulted,
        "contestability_notes": contestability_notes,
        "governance_notes": governance_notes,
        "bias_control": bias_control,
        "provider_lifecycle_review": provider_lifecycle_review,
        "provider_health_safety_risk": provider_health_safety_risk,
        "provider_fr_risk": provider_fr_risk,
        "provider_intended_purpose_risk": provider_intended_purpose_risk,
        "provider_misuse_risk": provider_misuse_risk,
        "misuse_assessed": misuse_assessed,
        "provider_post_market_link": provider_post_market_link,
        "provider_targeted_measures": provider_targeted_measures,
        "residual_risk_defined": residual_risk_defined,
        "provider_technical_evidence_available": provider_technical_evidence_available,
        "provider_article9_notes": provider_article9_notes,
        "deployer_process_description": deployer_process_description,
        "deployment_period": deployment_period,
        "deployment_frequency": deployment_frequency,
        "affected_categories_described": affected_categories_described,
        "provider_article13_info_used": provider_article13_info_used,
        "deployer_human_oversight_according_to_instructions": deployer_human_oversight_according_to_instructions,
        "risk_materialisation_measures": risk_materialisation_measures,
        "monitoring": monitoring,
        "deployer_process_evidence_available": deployer_process_evidence_available,
        "deployer_specific_harms": deployer_specific_harms,
        "deployer_governance_complaints": deployer_governance_complaints
    }

    scoping = compute_ai_scoping(inputs)
    risks = activate_fundamental_rights_risks(inputs, scoping)
    dpia_score, dpia_missing = compute_dpia_completeness(inputs)
    necessity = compute_necessity_judgment(inputs)
    proportionality = compute_proportionality_judgment(inputs, risks, scoping)
    information_gaps = compute_information_gaps(inputs, risks, scoping)
    flags = compute_red_flags(inputs, risks, scoping, necessity, proportionality, information_gaps)
    scrutiny_level = compute_scrutiny_level(inputs, flags, risks, necessity, proportionality, information_gaps)
    outcome = compute_outcome(flags, necessity, proportionality, information_gaps)

    st.session_state["last_assessment"] = {
        "inputs": inputs,
        "scoping": scoping,
        "risks": risks,
        "dpia_score": dpia_score,
        "dpia_missing": dpia_missing,
        "necessity": necessity,
        "proportionality": proportionality,
        "information_gaps": information_gaps,
        "flags": flags,
        "scrutiny_level": scrutiny_level,
        "outcome": outcome
    }


# ---------------------------------------------------------------------
# OUTPUT
# ---------------------------------------------------------------------

if "last_assessment" in st.session_state:
    result = st.session_state["last_assessment"]
    inputs = result["inputs"]
    scoping = result["scoping"]

    st.divider()
    st.header("Assessment result")

    col_a, col_b, col_c, col_d, col_e = st.columns(5)
    col_a.metric("DPIA completeness", f"{result['dpia_score']}%")
    col_b.metric("Necessity", result["necessity"]["status"])
    col_c.metric("Proportionality", result["proportionality"]["status"])
    col_d.metric("FR risks", len(result["risks"]))
    col_e.metric("Scrutiny", result["scrutiny_level"])

    st.subheader("Phase 0 scoping result")
    scope_cols = st.columns(3)
    scope_cols[0].info(f"AI-system status: **{scoping['ai_status']}**")
    scope_cols[1].info(f"GPAI status: **{scoping['gpai_status']}**")
    scope_cols[2].info(f"High-risk relevance: **{scoping['high_risk_status']}**")

    with st.expander("AI Act scoping audit trail", expanded=False):
        st.dataframe(pd.DataFrame(scoping["audit"]), use_container_width=True)

    st.subheader("Necessity judgment")
    if result["necessity"]["status"] == "Not demonstrated":
        st.error(result["necessity"]["explanation"])
    elif result["necessity"]["status"] == "Partially demonstrated":
        st.warning(result["necessity"]["explanation"])
    else:
        st.success(result["necessity"]["explanation"])
    st.dataframe(pd.DataFrame(result["necessity"]["audit"]), use_container_width=True)

    st.subheader("Proportionality judgment")
    if result["proportionality"]["status"] == "Not demonstrated":
        st.error(result["proportionality"]["explanation"])
    elif result["proportionality"]["status"] == "Partially demonstrated":
        st.warning(result["proportionality"]["explanation"])
    else:
        st.success(result["proportionality"]["explanation"])
    st.dataframe(pd.DataFrame(result["proportionality"]["audit"]), use_container_width=True)

    st.subheader("Recommended outcome")
    st.markdown(f"**{result['outcome']}**")

    st.subheader("Information gaps")
    if result["information_gaps"]:
        st.dataframe(pd.DataFrame(result["information_gaps"]), use_container_width=True)
    else:
        st.success("No information gaps detected.")

    st.subheader("Red flags")
    if result["flags"]:
        for level, message in result["flags"]:
            if level == "BLOCKING":
                st.error(f"{level}: {message}")
            elif level == "HIGH":
                st.warning(f"{level}: {message}")
            else:
                st.info(f"{level}: {message}")
    else:
        st.success("No red flags detected.")

    if result["dpia_missing"]:
        with st.expander("Missing or weak DPIA elements", expanded=False):
            for item in result["dpia_missing"]:
                st.write("-", item)

    st.subheader("Summary Fundamental Rights Risk Register")
    if result["risks"]:
        summary_register = build_summary_risk_register(result["risks"], result["flags"])
        st.dataframe(summary_register, use_container_width=True)
    else:
        st.info("No risk automatically activated. Manual legal review is required.")

    with st.expander("Operational Fundamental Rights Risk Register", expanded=False):
        if result["risks"]:
            operational_register = build_operational_risk_register(result["risks"], result["flags"])
            st.dataframe(operational_register, use_container_width=True)
        else:
            st.info("No operational risk register generated.")

    st.subheader("Editable Mitigation Action Plan")
    if result["risks"]:
        mitigation_plan = build_mitigation_action_plan(result["risks"], result["flags"])
        edited_mitigation_plan = st.data_editor(
            mitigation_plan,
            use_container_width=True,
            num_rows="dynamic",
            column_config={
                "Status": st.column_config.SelectboxColumn("Status", options=ACTION_STATUSES, required=True),
                "Residual risk after action": st.column_config.SelectboxColumn("Residual risk after action", options=RISK_LEVELS, required=True)
            }
        )
        st.session_state["edited_mitigation_plan"] = edited_mitigation_plan
    else:
        st.info("No mitigation action plan generated.")

    st.subheader("Final governance decision log")
    col_decision_1, col_decision_2 = st.columns(2)
    with col_decision_1:
        final_decision = st.selectbox("Final governance decision", GOVERNANCE_DECISIONS, index=GOVERNANCE_DECISIONS.index("To be decided"))
        decision_maker = st.text_input("Decision-maker / governance body", "")
        review_date = st.text_input("Review date", "")
    with col_decision_2:
        conditions_for_deployment = st.text_area("Conditions for deployment", "", placeholder="List mandatory safeguards, escalation duties, information requests or deployment conditions.")
        decision_reasoning = st.text_area("Decision reasoning", "", placeholder="Explain why residual risk is accepted, rejected, escalated or requires redesign.")

    final_decision_log = {
        "Final decision": final_decision,
        "Decision-maker": decision_maker,
        "Conditions for deployment": conditions_for_deployment,
        "Decision reasoning": decision_reasoning,
        "Review date": review_date
    }

    st.subheader("Download report")
    safe_file_name = inputs["project_name"].lower().replace(" ", "_").replace("/", "_") or "assessment"

    if result["risks"]:
        st.download_button(
            "Download Summary Risk Register CSV",
            build_summary_risk_register(result["risks"], result["flags"]).to_csv(index=False),
            file_name=f"{safe_file_name}_summary_risk_register.csv",
            mime="text/csv"
        )
        st.download_button(
            "Download Operational Risk Register CSV",
            build_operational_risk_register(result["risks"], result["flags"]).to_csv(index=False),
            file_name=f"{safe_file_name}_operational_risk_register.csv",
            mime="text/csv"
        )
        mitigation_download = st.session_state.get("edited_mitigation_plan", build_mitigation_action_plan(result["risks"], result["flags"]))
        st.download_button(
            "Download Mitigation Action Plan CSV",
            mitigation_download.to_csv(index=False),
            file_name=f"{safe_file_name}_mitigation_action_plan.csv",
            mime="text/csv"
        )

    if result["information_gaps"]:
        st.download_button(
            "Download Information Gaps CSV",
            pd.DataFrame(result["information_gaps"]).to_csv(index=False),
            file_name=f"{safe_file_name}_information_gaps.csv",
            mime="text/csv"
        )

    updated_report = build_report(result, final_decision_log)
    st.download_button(
        "Download Markdown report",
        updated_report,
        file_name=f"{safe_file_name}_fundamental_rights_assessment.md",
        mime="text/markdown"
    )

    json_payload = {
        "inputs": result["inputs"],
        "scoping": result["scoping"],
        "risks": result["risks"],
        "dpia_score": result["dpia_score"],
        "dpia_missing": result["dpia_missing"],
        "necessity": result["necessity"],
        "proportionality": result["proportionality"],
        "information_gaps": result["information_gaps"],
        "flags": result["flags"],
        "scrutiny_level": result["scrutiny_level"],
        "outcome": result["outcome"],
        "final_decision_log": final_decision_log,
        "generated_at": datetime.now().isoformat()
    }
    st.download_button(
        "Download JSON assessment",
        json.dumps(json_payload, ensure_ascii=False, indent=2),
        file_name=f"{safe_file_name}_assessment.json",
        mime="application/json"
    )
