import json
from datetime import datetime

import pandas as pd
import streamlit as st


# ---------------------------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------------------------

st.set_page_config(
    page_title="DPIA-based Fundamental Rights Assessment Tool",
    layout="wide"
)

st.title("DPIA-based Fundamental Rights Assessment Tool")
st.caption(
    "A DPIA-based workflow for identifying fundamental-rights risks, "
    "with role-specific AI Act add-ons for providers and deployers."
)


# ---------------------------------------------------------------------
# OPTIONS
# ---------------------------------------------------------------------

FILER_ROLES = [
    "Controller / data protection team",
    "Provider",
    "Deployer",
    "Joint assessment team",
    "Other"
]

CONTEXTS = [
    "Employment/HR",
    "Education",
    "Credit/insurance",
    "Welfare/public services",
    "Healthcare",
    "Justice/policing/migration",
    "Platforms/content",
    "Marketing/CRM",
    "Physical security/access",
    "Other"
]

ACTIONS = [
    "Scoring/ranking",
    "Classification",
    "Recommendation",
    "Exclusion/de-prioritisation",
    "Monitoring/surveillance",
    "Identity verification/biometrics",
    "Content moderation/ranking",
    "Risk prediction",
    "Content generation",
    "Other"
]

DATA_CATEGORIES = [
    "No personal data",
    "Common personal data",
    "Special categories of data",
    "Biometric data",
    "Inferred/profiling data",
    "Behavioural data",
    "Data from multiple sources",
    "Proxy variables",
    "Children's data"
]

DATA_SOURCES = [
    "Directly provided by the data subject",
    "Generated by the organisation",
    "Third-party data",
    "Publicly available data",
    "Sensor/IoT/log data",
    "Inferred data",
    "Combined datasets",
    "Other"
]

DECISION_EFFECTS = [
    "No significant effect",
    "Support to human decision",
    "Legal or similarly significant effect",
    "Access/exclusion/priority in services or opportunities"
]

GROUPS = [
    "Workers/candidates",
    "Students",
    "Patients",
    "Welfare beneficiaries",
    "Consumers",
    "Children",
    "Migrants/asylum seekers",
    "Persons with disabilities",
    "Protected or vulnerable groups",
    "General public"
]

LEGAL_BASES = [
    "To be determined",
    "Consent",
    "Contract",
    "Legal obligation",
    "Public interest",
    "Legitimate interest",
    "Vital interests",
    "Not applicable / to be verified"
]

DATA_SUBJECT_RIGHTS = [
    "Access",
    "Rectification",
    "Erasure",
    "Restriction",
    "Objection",
    "Portability",
    "Right not to be subject to solely automated decision-making where applicable",
    "Human intervention where applicable",
    "None / to be defined"
]

YES_NO_OPTIONS = [
    "Yes",
    "No",
    "Partly",
    "To be verified"
]

YES_NO_NA_OPTIONS = [
    "Yes",
    "No",
    "Partly",
    "Not applicable",
    "To be verified"
]

RISK_LEVELS = [
    "Low",
    "Medium",
    "High",
    "Very high",
    "To be verified"
]

FREQUENCY_OPTIONS = [
    "One-off",
    "Occasional",
    "Regular",
    "Continuous",
    "To be verified"
]

DATA_QUALITY_MEASURES = [
    "Data relevance check",
    "Data accuracy check",
    "Data completeness check",
    "Representativeness assessment",
    "Bias/proxy-variable analysis",
    "Outdated data removal",
    "Data lineage documentation",
    "Training/validation/test data separation",
    "Error correction procedure",
    "Ongoing data quality monitoring",
    "None / to be defined"
]

HUMAN_OVERSIGHT_MEASURES = [
    "Human-in-the-loop before final decision",
    "Human-on-the-loop monitoring",
    "Human override power",
    "Mandatory review for adverse outcomes",
    "Escalation to qualified reviewer",
    "Training against automation bias",
    "Documentation of human review",
    "Time and authority to depart from system output",
    "Periodic audit of human decisions",
    "None / to be defined"
]

CONTESTABILITY_MEASURES = [
    "Individual notice of AI-assisted decision",
    "Meaningful explanation of outcome",
    "Accessible complaint channel",
    "Human review upon request",
    "Possibility to correct input data",
    "Possibility to submit additional evidence",
    "Reasoned response to complaint",
    "Defined response deadlines",
    "Reversal or correction of adverse outcome",
    "Escalation to independent body or DPO",
    "None / to be defined"
]

GOVERNANCE_DECISIONS = [
    "GO",
    "CONDITIONAL GO",
    "REDESIGN REQUIRED",
    "NO-GO",
    "ESCALATE FOR REVIEW",
    "To be decided"
]

ACTION_STATUSES = [
    "To be started",
    "In progress",
    "Completed",
    "Not applicable",
    "Blocked"
]


# ---------------------------------------------------------------------
# FUNDAMENTAL RIGHTS RISK CATALOGUE
# ---------------------------------------------------------------------

RISK_CATALOG = [
    {
        "id": "FR1",
        "risk": "Excessive or disproportionate data processing",
        "rights": ["Privacy", "Data protection", "Informational self-determination"],
        "triggers": {
            "data_categories": [
                "Common personal data",
                "Special categories of data",
                "Biometric data",
                "Inferred/profiling data",
                "Behavioural data",
                "Data from multiple sources",
                "Children's data"
            ]
        },
        "mechanisms": [
            "Data minimisation failure",
            "Purpose creep",
            "Invisible inference",
            "Excessive retention",
            "Combination of datasets beyond reasonable expectations"
        ],
        "questions": [
            "Are all data strictly necessary for the stated purpose?",
            "Are inferred or derived data used?",
            "Is there a less intrusive alternative?",
            "Can the person exercise access, rectification, objection and restriction?"
        ],
        "safeguards": [
            "Data minimisation",
            "Purpose limitation",
            "Retention limits",
            "Clear information notice",
            "Effective data subject rights"
        ]
    },
    {
        "id": "FR2",
        "risk": "Direct, indirect or proxy discrimination",
        "rights": ["Equality", "Non-discrimination", "Equal access to opportunities"],
        "triggers": {
            "contexts": [
                "Employment/HR",
                "Education",
                "Credit/insurance",
                "Welfare/public services",
                "Healthcare",
                "Justice/policing/migration"
            ],
            "actions": [
                "Scoring/ranking",
                "Classification",
                "Exclusion/de-prioritisation",
                "Risk prediction"
            ],
            "data_categories": [
                "Special categories of data",
                "Biometric data",
                "Proxy variables",
                "Inferred/profiling data"
            ]
        },
        "mechanisms": [
            "Historical bias",
            "Proxy variables",
            "Unequal error rates",
            "Under-representation of groups",
            "Disparate impact"
        ],
        "questions": [
            "Are protected attributes or proxy variables used?",
            "Has the system been tested across affected groups?",
            "Do historical data reproduce previous inequalities?",
            "Does impact vary by gender, age, ethnic origin, disability, territory or socio-economic status?"
        ],
        "safeguards": [
            "Bias testing",
            "Subgroup analysis",
            "Independent audit",
            "Control of proxy variables",
            "Effective human review"
        ]
    },
    {
        "id": "FR3",
        "risk": "Decision-making opacity and insufficient explanation",
        "rights": ["Transparency", "Effective remedy", "Defence rights", "Good administration"],
        "triggers": {
            "actions": [
                "Scoring/ranking",
                "Classification",
                "Recommendation",
                "Risk prediction",
                "Exclusion/de-prioritisation"
            ],
            "decision_effects": [
                "Legal or similarly significant effect",
                "Access/exclusion/priority in services or opportunities"
            ]
        },
        "mechanisms": [
            "Opaque criteria",
            "Unexplained score",
            "Unclear role of automation",
            "Inability to understand the reason for the outcome"
        ],
        "questions": [
            "Does the person know that the system is used?",
            "Can the essential logic be explained in understandable terms?",
            "Can the person know the relevant criteria?",
            "Does the explanation enable concrete contestation?"
        ],
        "safeguards": [
            "Individual notice",
            "Understandable explanation",
            "Documentation of decision criteria",
            "Appeal channel",
            "Decision logging"
        ]
    },
    {
        "id": "FR4",
        "risk": "Ineffective or merely formal human oversight",
        "rights": ["Accountability", "Effective remedy", "Due process", "Good administration"],
        "triggers": {
            "actions": [
                "Recommendation",
                "Scoring/ranking",
                "Risk prediction",
                "Exclusion/de-prioritisation"
            ],
            "decision_effects": [
                "Support to human decision",
                "Legal or similarly significant effect",
                "Access/exclusion/priority in services or opportunities"
            ]
        },
        "mechanisms": [
            "Automation bias",
            "Rubber-stamping",
            "Lack of authority to override",
            "Lack of time or competence for review"
        ],
        "questions": [
            "Can the human reviewer genuinely depart from the system output?",
            "Does the reviewer have time, competence and authority?",
            "Are automation bias and rubber-stamping prevented?",
            "Is the human review documented?"
        ],
        "safeguards": [
            "Reviewer training",
            "Override right",
            "Documented review",
            "Anti-automation-bias procedure",
            "Periodic control of confirmed decisions"
        ]
    },
    {
        "id": "FR5",
        "risk": "Exclusion from essential goods, services or opportunities",
        "rights": ["Access to services", "Substantive equality", "Dignity", "Effective remedy"],
        "triggers": {
            "contexts": [
                "Employment/HR",
                "Education",
                "Credit/insurance",
                "Welfare/public services",
                "Healthcare",
                "Justice/policing/migration"
            ],
            "actions": [
                "Exclusion/de-prioritisation",
                "Scoring/ranking",
                "Classification"
            ],
            "decision_effects": [
                "Access/exclusion/priority in services or opportunities",
                "Legal or similarly significant effect"
            ]
        },
        "mechanisms": [
            "Denial of access",
            "De-prioritisation",
            "Loss of opportunity",
            "Irreversible or time-sensitive harm"
        ],
        "questions": [
            "Can the output restrict access to an essential service or opportunity?",
            "Is there a non-automated alternative channel?",
            "Can an error be corrected in due time?",
            "Is the harm reversible?"
        ],
        "safeguards": [
            "Alternative channel",
            "Urgent review",
            "Human fallback",
            "Outcome notification",
            "Remedy procedure"
        ]
    },
    {
        "id": "FR6",
        "risk": "Disproportionate surveillance and chilling effect",
        "rights": [
            "Privacy",
            "Personal liberty",
            "Freedom of expression",
            "Freedom of association",
            "Dignity"
        ],
        "triggers": {
            "actions": [
                "Monitoring/surveillance",
                "Identity verification/biometrics",
                "Content moderation/ranking"
            ],
            "data_categories": [
                "Biometric data",
                "Behavioural data",
                "Data from multiple sources",
                "Inferred/profiling data"
            ]
        },
        "mechanisms": [
            "Continuous observation",
            "Behavioural adaptation due to being monitored",
            "Excessive identification",
            "Function creep"
        ],
        "questions": [
            "Is monitoring continuous or systematic?",
            "May persons change behaviour because they feel observed?",
            "Is the measure strictly necessary?",
            "Are there temporal and functional limits?"
        ],
        "safeguards": [
            "Temporal limitation",
            "Purpose limitation",
            "Reduced data granularity",
            "Enhanced transparency",
            "Monitoring audit"
        ]
    },
    {
        "id": "FR7",
        "risk": "Dignity, autonomy and stigmatisation",
        "rights": [
            "Dignity",
            "Individual autonomy",
            "Reputation",
            "Free development of personality"
        ],
        "triggers": {
            "actions": [
                "Risk prediction",
                "Scoring/ranking",
                "Classification",
                "Monitoring/surveillance"
            ],
            "data_categories": [
                "Inferred/profiling data",
                "Behavioural data",
                "Biometric data"
            ]
        },
        "mechanisms": [
            "Reduction of the person to a score",
            "Stigmatising labels",
            "Predictive categorisation",
            "Loss of self-determination"
        ],
        "questions": [
            "Is the person reduced to a score, profile or category?",
            "Does the system assign reliability, risk, productivity or social value?",
            "Can the label generate stigma?",
            "Can the person correct or contest the classification?"
        ],
        "safeguards": [
            "Limit categories",
            "Avoid stigmatising labels",
            "Individual explanation",
            "Profile correction",
            "Qualified human review"
        ]
    },
    {
        "id": "FR8",
        "risk": "Freedom of expression, information and pluralism",
        "rights": [
            "Freedom of expression",
            "Freedom of information",
            "Pluralism",
            "Contestability"
        ],
        "triggers": {
            "contexts": ["Platforms/content"],
            "actions": [
                "Content moderation/ranking",
                "Recommendation",
                "Exclusion/de-prioritisation",
                "Content generation"
            ]
        },
        "mechanisms": [
            "Over-removal",
            "Under-removal",
            "Opacity of ranking",
            "Distortion of visibility",
            "Chilling effect"
        ],
        "questions": [
            "Does the system remove, downrank or order content?",
            "Can it produce over-removal or under-removal?",
            "Does it affect the visibility of groups, opinions or information?",
            "Is there an effective and timely appeal?"
        ],
        "safeguards": [
            "Transparent ranking/moderation criteria",
            "User notice",
            "Appeal",
            "Audit of over-removal and under-removal",
            "Monitoring of systemic effects"
        ]
    },
    {
        "id": "FR9",
        "risk": "Accountability gap and unclear allocation of responsibilities",
        "rights": ["Accountability", "Effective remedy", "Effective protection of rights"],
        "triggers": {
            "actions": [
                "Scoring/ranking",
                "Classification",
                "Recommendation",
                "Risk prediction",
                "Content generation",
                "Other"
            ]
        },
        "mechanisms": [
            "Unclear role allocation",
            "Responsibility shifting",
            "Lack of internal owner",
            "Fragmented provider-deployer-controller responsibilities"
        ],
        "questions": [
            "Is it clear who decides?",
            "Is it clear who controls?",
            "Is it clear who is responsible for error or harm?",
            "Are provider, deployer, controller, processor and internal owners distinguished?"
        ],
        "safeguards": [
            "Accountability matrix",
            "Internal owners",
            "Logging",
            "Audit trail",
            "Escalation procedure"
        ]
    },
    {
        "id": "FR10",
        "risk": "Ineffective remedy or impossibility of contestation",
        "rights": ["Effective remedy", "Due process", "Defence rights", "Good administration"],
        "triggers": {
            "actions": [
                "Scoring/ranking",
                "Classification",
                "Exclusion/de-prioritisation",
                "Risk prediction",
                "Content moderation/ranking"
            ],
            "decision_effects": [
                "Legal or similarly significant effect",
                "Access/exclusion/priority in services or opportunities"
            ]
        },
        "mechanisms": [
            "No complaint channel",
            "Complaint without effect",
            "No human review",
            "No reasons given",
            "Excessive burden on affected person"
        ],
        "questions": [
            "Can the person contest the outcome?",
            "Is the complaint channel simple, accessible and timely?",
            "Can contestation concretely change the outcome?",
            "Are response deadlines defined?"
        ],
        "safeguards": [
            "Complaint mechanism",
            "Human channel",
            "Response deadlines",
            "Reasoned outcome",
            "Possibility of review"
        ]
    },
    {
        "id": "FR11",
        "risk": "Health or safety harm with fundamental-rights implications",
        "rights": [
            "Right to life",
            "Physical and mental integrity",
            "Health protection",
            "Dignity",
            "Non-discrimination"
        ],
        "triggers": {
            "contexts": [
                "Healthcare",
                "Physical security/access",
                "Justice/policing/migration",
                "Employment/HR",
                "Welfare/public services"
            ]
        },
        "mechanisms": [
            "Unsafe output",
            "Incorrect risk classification",
            "Delayed intervention",
            "False positives or false negatives",
            "Unequal exposure to physical or psychological harm"
        ],
        "questions": [
            "Can system errors create physical, psychological or safety-related harm?",
            "Are some groups more exposed to such harm?",
            "Can the harm materialise before human correction is possible?",
            "Are emergency fallback and escalation mechanisms available?"
        ],
        "safeguards": [
            "Safety testing",
            "Emergency fallback",
            "Incident escalation",
            "Human override",
            "Monitoring of adverse events"
        ]
    }
]


# ---------------------------------------------------------------------
# FUNCTIONS
# ---------------------------------------------------------------------

def has_intersection(values, triggers):
    return bool(set(values).intersection(set(triggers)))


def is_provider_role(inputs):
    return (
        "Provider" in inputs["filer_role"]
        or "Joint assessment team" in inputs["filer_role"]
    )


def is_deployer_role(inputs):
    return (
        "Deployer" in inputs["filer_role"]
        or "Joint assessment team" in inputs["filer_role"]
    )


def no_measure_selected(measures):
    return "None / to be defined" in measures or len(measures) == 0


def is_missing_text(value):
    return value is None or str(value).strip() == ""


def compute_dpia_completeness(inputs):
    checks = [
        ("Purpose described", not is_missing_text(inputs["purpose"])),
        ("Processing operation described", not is_missing_text(inputs["processing_description"])),
        ("Operational context described", not is_missing_text(inputs["processing_context"])),
        ("Legal basis identified", inputs["legal_basis"] not in ["To be determined", "Not applicable / to be verified"]),
        ("Purpose specificity assessed", inputs["purpose_specificity"] == "Yes"),
        ("Legal basis adequacy assessed", inputs["legal_basis_adequacy"] == "Yes"),
        ("Purpose compatibility assessed", inputs["purpose_compatibility"] in ["Yes", "Not applicable"]),
        ("Data categories selected", len(inputs["data_categories"]) > 0),
        ("Data sources selected", len(inputs["data_sources"]) > 0),
        ("Data minimisation assessed", inputs["data_minimisation"] == "Yes"),
        ("Retention limits defined", inputs["retention_limits"] == "Yes"),
        ("Data subjects identified", len(inputs["data_subjects"]) > 0),
        ("Vulnerability reasoning provided", inputs["vulnerable_subjects"] != "Yes" or not is_missing_text(inputs["vulnerability_reasoning"])),
        ("Transparency ensured", inputs["transparency_notice"] == "Yes"),
        ("Data-subject rights operationalised", "None / to be defined" not in inputs["data_subject_rights"]),
        ("Less intrusive alternatives assessed", inputs["alternatives_assessed"] == "Yes"),
        ("Necessity reasoning provided", not is_missing_text(inputs["necessity_reasoning"])),
        ("Proportionality reasoning provided", not is_missing_text(inputs["proportionality_reasoning"])),
        ("DPIA risk described", not is_missing_text(inputs["dpia_risk_description"]))
    ]

    completed = sum(1 for _, ok in checks if ok)
    total = len(checks)
    score = round((completed / total) * 100)

    missing = [name for name, ok in checks if not ok]

    return score, missing


def compute_coherence_warnings(inputs):
    warnings = []

    sensitive_contexts = {
        "Employment/HR",
        "Education",
        "Credit/insurance",
        "Welfare/public services",
        "Healthcare",
        "Justice/policing/migration"
    }

    vulnerable_groups = {
        "Children",
        "Migrants/asylum seekers",
        "Persons with disabilities",
        "Protected or vulnerable groups",
        "Welfare beneficiaries",
        "Patients"
    }

    risky_actions = {
        "Scoring/ranking",
        "Classification",
        "Exclusion/de-prioritisation",
        "Risk prediction",
        "Monitoring/surveillance",
        "Identity verification/biometrics"
    }

    if inputs["decision_effect"] == "No significant effect":
        if set(inputs["contexts"]).intersection(sensitive_contexts):
            warnings.append(
                "Coherence warning: 'No significant effect' was selected, but the deployment context is sensitive."
            )

        if set(inputs["groups"]).intersection(vulnerable_groups) or inputs["vulnerable_subjects"] == "Yes":
            warnings.append(
                "Coherence warning: 'No significant effect' was selected, but vulnerable persons or groups are involved."
            )

        if set(inputs["actions"]).intersection(risky_actions):
            warnings.append(
                "Coherence warning: 'No significant effect' was selected, but the system action may affect persons or opportunities."
            )

        if inputs["power_asymmetry"] == "Yes":
            warnings.append(
                "Coherence warning: 'No significant effect' was selected despite a significant power asymmetry."
            )

    if inputs["dpia_risk_to_rights"] == "Low" and inputs["dpia_high_risk"] == "Yes":
        warnings.append(
            "Coherence warning: baseline DPIA risk is marked as Low, but the processing is also marked as likely high-risk after safeguards."
        )

    if inputs["data_quality_residual_risk"] == "Low" and no_measure_selected(inputs["data_quality_measures"]):
        warnings.append(
            "Coherence warning: residual data-quality risk is Low, but no concrete data-quality measures are defined."
        )

    if inputs["human_oversight_residual_risk"] == "Low" and no_measure_selected(inputs["human_oversight_measures"]):
        warnings.append(
            "Coherence warning: residual human-oversight risk is Low, but no concrete oversight measures are defined."
        )

    if inputs["contestability_residual_risk"] == "Low" and no_measure_selected(inputs["contestability_measures"]):
        warnings.append(
            "Coherence warning: residual contestability risk is Low, but no concrete contestability measures are defined."
        )

    return warnings


def activate_fundamental_rights_risks(inputs):
    activated = []

    for item in RISK_CATALOG:
        matched = []
        triggers = item["triggers"]

        if "contexts" in triggers and has_intersection(inputs["contexts"], triggers["contexts"]):
            matched.append("deployment context")

        if "actions" in triggers and has_intersection(inputs["actions"], triggers["actions"]):
            matched.append("system action")

        if "data_categories" in triggers and has_intersection(inputs["data_categories"], triggers["data_categories"]):
            matched.append("data category")

        if "decision_effects" in triggers and inputs["decision_effect"] in triggers["decision_effects"]:
            matched.append("effect on persons or opportunities")

        if matched:
            activated.append({
                "ID": item["id"],
                "Fundamental rights risk": item["risk"],
                "Rights involved": "; ".join(item["rights"]),
                "Legal mechanisms of harm": "; ".join(item["mechanisms"]),
                "Triggered by": ", ".join(matched),
                "Questions for legal analysis": " | ".join(item["questions"]),
                "Safeguards to test": " | ".join(item["safeguards"])
            })

    if is_provider_role(inputs):
        if inputs["provider_health_safety_risk"] in ["High", "Very high"]:
            activated.append({
                "ID": "FR-A9-HS",
                "Fundamental rights risk": "Health and safety risk with spill-over effects on fundamental rights",
                "Rights involved": "Health protection; physical and mental integrity; dignity; equality",
                "Legal mechanisms of harm": (
                    "Safety-related malfunction; unsafe output; delayed correction; "
                    "unequal exposure to harmful consequences"
                ),
                "Triggered by": "provider-side Article 9 health/safety risk estimation",
                "Questions for legal analysis": (
                    "Does the safety or health risk also affect dignity, equality, autonomy or access to services? | "
                    "Are vulnerable groups disproportionately exposed? | "
                    "Can the harm be corrected before it materialises?"
                ),
                "Safeguards to test": (
                    "Targeted risk-control measures | safety testing | incident escalation | "
                    "human override | monitoring of adverse events"
                )
            })

        if inputs["provider_misuse_risk"] in ["High", "Very high"]:
            activated.append({
                "ID": "FR-A9-MISUSE",
                "Fundamental rights risk": "Reasonably foreseeable misuse creating fundamental-rights harm",
                "Rights involved": "Privacy; non-discrimination; dignity; effective remedy; accountability",
                "Legal mechanisms of harm": (
                    "Use outside intended purpose; foreseeable organisational misuse; "
                    "over-reliance; function creep"
                ),
                "Triggered by": "provider-side Article 9 misuse risk estimation",
                "Questions for legal analysis": (
                    "What harmful uses are reasonably foreseeable? | "
                    "Can design, documentation or restrictions reduce such misuse? | "
                    "Who is responsible for preventing foreseeable misuse?"
                ),
                "Safeguards to test": (
                    "Use restrictions | instructions for use | technical guardrails | "
                    "logging | user training | escalation duties"
                )
            })

    if is_deployer_role(inputs):
        if inputs["deployment_frequency"] in ["Regular", "Continuous"]:
            activated.append({
                "ID": "FR-A27-SCALE",
                "Fundamental rights risk": "Repeated or continuous deployment increasing cumulative rights impact",
                "Rights involved": "Privacy; equality; dignity; effective remedy; access to services",
                "Legal mechanisms of harm": (
                    "Cumulative exposure; normalisation of automated decision-making; "
                    "systemic exclusion; repeated surveillance or classification"
                ),
                "Triggered by": "deployer-side Article 27 period/frequency of use",
                "Questions for legal analysis": (
                    "Does repeated use increase cumulative harm? | "
                    "Are periodic reviews scheduled? | "
                    "Can affected persons detect and contest repeated adverse effects?"
                ),
                "Safeguards to test": (
                    "Periodic review | cumulative-impact monitoring | complaint analysis | "
                    "sampling of decisions | suspension trigger"
                )
            })

        if inputs["risk_materialisation_measures"] in ["No", "To be verified"]:
            activated.append({
                "ID": "FR-A27-MATERIALISATION",
                "Fundamental rights risk": "Insufficient measures in case of materialisation of rights-related harm",
                "Rights involved": "Effective remedy; accountability; due process; good administration",
                "Legal mechanisms of harm": (
                    "No internal escalation; no complaint handling; delayed correction; "
                    "lack of remedial pathway after harm occurs"
                ),
                "Triggered by": "deployer-side Article 27 risk-materialisation measures",
                "Questions for legal analysis": (
                    "What happens when the risk materialises? | "
                    "Who acts, within what deadline, and with what powers? | "
                    "Can the individual obtain correction or reversal?"
                ),
                "Safeguards to test": (
                    "Incident response | complaint mechanism | internal governance | "
                    "remedial deadlines | suspension or rollback procedure"
                )
            })

    return activated


def classify_risk_source(risk_id):
    if risk_id.startswith("FR-A9"):
        return "Article 9 provider add-on"
    if risk_id.startswith("FR-A27"):
        return "Article 27 deployer add-on"
    if risk_id == "FR1":
        return "DPIA data-processing layer"
    return "Fundamental-rights legal risk layer"


def compute_red_flags(inputs, risks):
    flags = []
    risk_ids = {risk["ID"] for risk in risks}

    significant_decision = inputs["decision_effect"] in [
        "Legal or similarly significant effect",
        "Access/exclusion/priority in services or opportunities"
    ]

    sensitive_data = {
        "Special categories of data",
        "Biometric data",
        "Children's data"
    }

    if not inputs["purpose"].strip():
        flags.append(("BLOCKING", "DPIA core: purpose is missing or insufficiently specified."))

    if inputs["legal_basis"] in ["To be determined", "Not applicable / to be verified"]:
        flags.append(("BLOCKING", "DPIA core: legal basis is not clearly identified."))

    if inputs["purpose_specificity"] in ["No", "To be verified"]:
        flags.append(("BLOCKING", "DPIA core: the purpose is not sufficiently specific, explicit and determined."))

    if inputs["legal_basis_adequacy"] in ["No", "To be verified"]:
        flags.append(("BLOCKING", "DPIA core: the adequacy of the legal basis is not demonstrated."))

    if inputs["purpose_compatibility"] in ["No", "To be verified"]:
        flags.append(("HIGH", "DPIA core: purpose compatibility or further-processing compatibility is not sufficiently assessed."))

    if set(inputs["data_categories"]).intersection(sensitive_data) and inputs["data_necessary"] != "Yes":
        flags.append(("HIGH", "DPIA core: sensitive, biometric or children's data are used without a strict necessity justification."))

    if inputs["data_minimisation"] in ["No", "To be verified"]:
        flags.append(("HIGH", "DPIA core: data minimisation is not sufficiently demonstrated."))

    if inputs["retention_limits"] in ["No", "To be verified"]:
        flags.append(("MEDIUM", "DPIA core: storage limitation and deletion periods are not clearly defined."))

    if inputs["vulnerable_subjects"] == "Yes" and not inputs["vulnerability_reasoning"].strip():
        flags.append(("HIGH", "DPIA core: vulnerable persons or groups are involved but vulnerability reasoning is missing."))

    if inputs["power_asymmetry"] == "Yes" and not inputs["vulnerability_reasoning"].strip():
        flags.append(("HIGH", "DPIA core: power asymmetry is present but not explained."))

    if inputs["transparency_notice"] in ["No", "To be verified"]:
        flags.append(("HIGH", "DPIA core: transparency towards affected persons is not sufficiently ensured."))

    if "None / to be defined" in inputs["data_subject_rights"]:
        flags.append(("HIGH", "DPIA core: data-subject rights are not operationally supported."))

    if inputs["alternatives_assessed"] in ["No", "To be verified"]:
        flags.append(("HIGH", "DPIA core: less intrusive alternatives have not been sufficiently assessed."))

    if inputs["dpia_high_risk"] == "Yes":
        flags.append(("HIGH", "DPIA core: processing remains likely to result in high risk after initial safeguards."))

    if inputs["data_quality_assessed"] in ["No", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: data quality has not been sufficiently assessed."))

    if no_measure_selected(inputs["data_quality_measures"]):
        flags.append(("HIGH", "Mitigation layer: data quality measures are missing or still to be defined."))

    if inputs["data_quality_residual_risk"] in ["High", "Very high"]:
        flags.append(("HIGH", "Mitigation layer: residual risk after data quality measures remains high."))

    if "FR2" in risk_ids and inputs["bias_control"] in ["No", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: discrimination risk is present, but bias/proxy-control safeguards are not sufficiently demonstrated."))

    if significant_decision and inputs["human_oversight"] in ["Absent", "Merely formal", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: human oversight is absent, merely formal or insufficiently demonstrated in a significant decision-making context."))

    if significant_decision and no_measure_selected(inputs["human_oversight_measures"]):
        flags.append(("HIGH", "Mitigation layer: human oversight measures are missing or still to be defined in a significant decision-making context."))

    if inputs["human_oversight_residual_risk"] in ["High", "Very high"]:
        flags.append(("HIGH", "Mitigation layer: residual risk after human oversight measures remains high."))

    if significant_decision and inputs["contestability"] != "Yes":
        flags.append(("BLOCKING", "Mitigation layer: affected persons cannot effectively contest a significant outcome."))

    if significant_decision and inputs["remedy_effectiveness"] in ["No", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: the remedy is not shown to be capable of changing the outcome."))

    if significant_decision and no_measure_selected(inputs["contestability_measures"]):
        flags.append(("BLOCKING", "Mitigation layer: contestability measures are missing or still to be defined in a significant decision-making context."))

    if inputs["contestability_residual_risk"] in ["High", "Very high"]:
        flags.append(("HIGH", "Mitigation layer: residual risk after contestability measures remains high."))

    if "FR10" in risk_ids and inputs["remedy_effectiveness"] != "Yes":
        flags.append(("HIGH", "Mitigation layer: a remedy risk is present, but remedy effectiveness is not demonstrated."))

    if "FR5" in risk_ids and inputs["fallback_channel"] in ["No", "To be verified"]:
        flags.append(("HIGH", "Mitigation layer: potential exclusion from services or opportunities is present without a reliable fallback channel."))

    if not inputs["accountability_owner"].strip():
        flags.append(("HIGH", "Accountability: internal accountability owner is missing."))

    if is_provider_role(inputs):
        if inputs["provider_lifecycle_review"] in ["No", "To be verified"]:
            flags.append(("MEDIUM", "Article 9 provider add-on: lifecycle review and updating are not clearly established."))

        if inputs["provider_health_safety_risk"] in ["High", "Very high"] and inputs["provider_targeted_measures"] != "Yes":
            flags.append(("HIGH", "Article 9 provider add-on: high health/safety risk without targeted risk-management measures."))

        if inputs["provider_fr_risk"] in ["High", "Very high"] and inputs["provider_targeted_measures"] != "Yes":
            flags.append(("HIGH", "Article 9 provider add-on: high fundamental-rights risk without targeted risk-management measures."))

        if inputs["provider_misuse_risk"] in ["High", "Very high"] and inputs["misuse_assessed"] != "Yes":
            flags.append(("HIGH", "Article 9 provider add-on: high misuse risk is not sufficiently assessed."))

        if inputs["provider_post_market_link"] in ["No", "To be verified"]:
            flags.append(("MEDIUM", "Article 9 provider add-on: post-market monitoring feedback is not linked to risk review."))

    if is_deployer_role(inputs):
        if inputs["deployer_process_description"].strip() == "":
            flags.append(("HIGH", "Article 27 deployer add-on: the deployer's process in which the AI system will be used is not described."))

        if inputs["affected_categories_described"] != "Yes":
            flags.append(("HIGH", "Article 27 deployer add-on: affected persons and groups are not sufficiently described."))

        if inputs["provider_article13_info_used"] in ["No", "To be verified"]:
            flags.append(("MEDIUM", "Article 27 deployer add-on: provider information/instructions have not been used or verified."))

        if inputs["deployer_human_oversight_according_to_instructions"] in ["No", "To be verified"]:
            flags.append(("HIGH", "Article 27 deployer add-on: implementation of human oversight according to instructions is not demonstrated."))

        if inputs["risk_materialisation_measures"] in ["No", "To be verified"]:
            flags.append(("HIGH", "Article 27 deployer add-on: measures in case of materialisation of risks are missing or insufficient."))

        if inputs["monitoring"] != "Yes":
            flags.append(("MEDIUM", "Article 27 deployer add-on: post-deployment monitoring is not clearly established."))

    return flags


def compute_scrutiny_level(inputs, flags, risks):
    score = 0

    high_contexts = {"Employment/HR", "Education", "Credit/insurance", "Welfare/public services", "Healthcare"}
    very_high_contexts = {"Justice/policing/migration"}
    vulnerable_groups = {
        "Children",
        "Migrants/asylum seekers",
        "Persons with disabilities",
        "Protected or vulnerable groups",
        "Welfare beneficiaries",
        "Patients"
    }
    sensitive_data = {"Special categories of data", "Biometric data", "Children's data"}

    if set(inputs["contexts"]).intersection(high_contexts):
        score += 2

    if set(inputs["contexts"]).intersection(very_high_contexts):
        score += 3

    if set(inputs["groups"]).intersection(vulnerable_groups):
        score += 3

    if set(inputs["data_categories"]).intersection(sensitive_data):
        score += 3

    if inputs["decision_effect"] in ["Legal or similarly significant effect", "Access/exclusion/priority in services or opportunities"]:
        score += 3

    if inputs["dpia_risk_to_rights"] in ["High", "Very high"]:
        score += 3

    if inputs["dpia_high_risk"] == "Yes":
        score += 3

    if inputs["vulnerable_subjects"] == "Yes":
        score += 2

    if inputs["power_asymmetry"] == "Yes":
        score += 2

    if inputs["data_quality_residual_risk"] in ["High", "Very high"]:
        score += 2

    if inputs["human_oversight_residual_risk"] in ["High", "Very high"]:
        score += 2

    if inputs["contestability_residual_risk"] in ["High", "Very high"]:
        score += 2

    if is_provider_role(inputs):
        if inputs["provider_health_safety_risk"] in ["High", "Very high"]:
            score += 2
        if inputs["provider_fr_risk"] in ["High", "Very high"]:
            score += 3
        if inputs["provider_misuse_risk"] in ["High", "Very high"]:
            score += 2

    if is_deployer_role(inputs):
        if inputs["deployment_frequency"] in ["Regular", "Continuous"]:
            score += 2
        if inputs["affected_categories_described"] != "Yes":
            score += 2

    if len(risks) >= 5:
        score += 2

    if any(level == "BLOCKING" for level, _ in flags):
        score += 4

    if score >= 11:
        return "Very high"

    if score >= 7:
        return "High"

    if score >= 3:
        return "Medium"

    return "Low"


def compute_outcome(flags, scrutiny_level):
    levels = [level for level, _ in flags]

    if "BLOCKING" in levels:
        return "NO-GO / redesign required before deployment"

    if "HIGH" in levels:
        return "CONDITIONAL GO with mandatory safeguards and escalation"

    if scrutiny_level in ["High", "Very high"]:
        return "CONDITIONAL GO / enhanced human-rights review"

    if "MEDIUM" in levels:
        return "GO with documented review and monitoring"

    return "GO"


def compute_risk_priority(risk, inputs, flags):
    risk_id = risk["ID"]

    significant_decision = inputs["decision_effect"] in [
        "Legal or similarly significant effect",
        "Access/exclusion/priority in services or opportunities"
    ]

    vulnerable_context = (
        inputs["vulnerable_subjects"] == "Yes"
        or inputs["power_asymmetry"] == "Yes"
        or any(group in inputs["groups"] for group in [
            "Children",
            "Migrants/asylum seekers",
            "Persons with disabilities",
            "Protected or vulnerable groups",
            "Welfare beneficiaries",
            "Patients"
        ])
    )

    has_blocking = any(level == "BLOCKING" for level, _ in flags)
    has_high = any(level == "HIGH" for level, _ in flags)

    if risk_id in ["FR10", "FR4"] and significant_decision:
        if inputs["contestability"] != "Yes" or inputs["human_oversight"] in ["Absent", "Merely formal", "To be verified"]:
            return "Very high"

    if risk_id == "FR2":
        if inputs["bias_control"] in ["No", "To be verified"] or inputs["data_quality_residual_risk"] in ["High", "Very high"]:
            return "Very high"

    if risk_id in ["FR5", "FR-A27-MATERIALISATION"]:
        if inputs["fallback_channel"] in ["No", "To be verified"] or inputs["risk_materialisation_measures"] in ["No", "To be verified"]:
            return "Very high"

    if risk_id.startswith("FR-A9"):
        if inputs["provider_health_safety_risk"] in ["High", "Very high"] or inputs["provider_fr_risk"] in ["High", "Very high"]:
            return "High"

    if vulnerable_context and significant_decision:
        return "High"

    if has_blocking or has_high:
        return "High"

    return "Medium"


def suggested_actions_for_risk(risk_id):
    action_map = {
        "FR1": [
            ("Review data minimisation and retention", "Data inventory; minimisation memo; retention schedule"),
            ("Verify data-subject rights workflow", "Rights request procedure; response-time evidence")
        ],
        "FR2": [
            ("Perform bias and proxy-variable analysis", "Bias testing report; subgroup performance analysis"),
            ("Review representativeness of datasets", "Dataset documentation; representativeness assessment")
        ],
        "FR3": [
            ("Prepare meaningful explanation of outcome", "Explanation template; decision criteria documentation"),
            ("Document role of AI in the decision", "Transparency notice; internal decision-flow map")
        ],
        "FR4": [
            ("Strengthen human oversight", "Human oversight procedure; override protocol"),
            ("Train reviewers against automation bias", "Training material; attendance log; review audit")
        ],
        "FR5": [
            ("Create fallback or alternative access channel", "Fallback procedure; escalation workflow"),
            ("Define urgent review for adverse outcomes", "Review deadlines; escalation matrix")
        ],
        "FR6": [
            ("Limit monitoring scope and duration", "Monitoring policy; purpose limitation statement"),
            ("Assess chilling-effect risk", "Impact analysis; stakeholder consultation evidence")
        ],
        "FR7": [
            ("Review profiling and labelling logic", "Profile taxonomy; label-risk review"),
            ("Enable correction or challenge of classification", "Correction workflow; appeal procedure")
        ],
        "FR8": [
            ("Audit content ranking or moderation effects", "Moderation/ranking audit; over-removal analysis"),
            ("Create effective appeal for content decisions", "Appeal workflow; user notice")
        ],
        "FR9": [
            ("Create accountability matrix", "RACI matrix; internal governance document"),
            ("Define escalation and audit trail", "Escalation procedure; logging policy")
        ],
        "FR10": [
            ("Create accessible complaint mechanism", "Complaint workflow; public/internal instructions"),
            ("Ensure remedy can change the outcome", "Review powers; reversal/correction procedure")
        ],
        "FR11": [
            ("Perform safety and adverse-event testing", "Safety testing report; incident logs"),
            ("Define emergency fallback and escalation", "Incident response plan; emergency override procedure")
        ],
        "FR-A9-HS": [
            ("Adopt targeted health/safety risk-control measures", "Safety risk register; targeted mitigation plan"),
            ("Link safety incidents to lifecycle risk review", "Lifecycle review log; post-market monitoring evidence")
        ],
        "FR-A9-MISUSE": [
            ("Assess and document foreseeable misuse scenarios", "Misuse analysis; use restriction documentation"),
            ("Add guardrails and instructions for use", "Instructions for use; technical/organisational guardrails")
        ],
        "FR-A27-SCALE": [
            ("Monitor cumulative impact of repeated deployment", "Periodic review report; complaint trend analysis"),
            ("Define suspension trigger for cumulative harm", "Suspension criteria; governance decision log")
        ],
        "FR-A27-MATERIALISATION": [
            ("Define measures if risks materialise", "Incident response plan; complaint escalation workflow"),
            ("Assign internal governance owner", "RACI matrix; owner appointment; response deadlines")
        ]
    }

    return action_map.get(risk_id, [("Perform manual legal review", "Legal assessment note; governance decision")])


def suggest_owner_for_action(action):
    action_lower = action.lower()

    if "data" in action_lower or "dataset" in action_lower or "minimisation" in action_lower:
        return "DPO / Data governance lead"

    if "bias" in action_lower or "subgroup" in action_lower or "testing" in action_lower:
        return "AI governance / Model validation team"

    if "human oversight" in action_lower or "reviewer" in action_lower or "override" in action_lower:
        return "Business process owner / Human oversight lead"

    if "complaint" in action_lower or "remedy" in action_lower or "appeal" in action_lower:
        return "Legal / Complaints handling team"

    if "safety" in action_lower or "incident" in action_lower or "emergency" in action_lower:
        return "Risk management / Safety owner"

    if "accountability" in action_lower or "governance" in action_lower or "raci" in action_lower:
        return "AI governance officer"

    return "Assessment owner"


def build_operational_risk_register(risks, inputs, flags):
    rows = []

    for risk in risks:
        risk_id = risk["ID"]
        rows.append({
            "Risk ID": risk_id,
            "Risk source": classify_risk_source(risk_id),
            "Priority": compute_risk_priority(risk, inputs, flags),
            "Fundamental rights risk": risk["Fundamental rights risk"],
            "Rights involved": risk["Rights involved"],
            "Triggered by": risk["Triggered by"],
            "Required safeguards to test": risk["Safeguards to test"],
            "Residual risk reference": (
                "Data quality: "
                + inputs["data_quality_residual_risk"]
                + " | Human oversight: "
                + inputs["human_oversight_residual_risk"]
                + " | Contestability: "
                + inputs["contestability_residual_risk"]
            ),
            "Assessment status": "Open"
        })

    return pd.DataFrame(rows)


def build_summary_risk_register(risks, inputs, flags):
    rows = []

    for risk in risks:
        risk_id = risk["ID"]
        rows.append({
            "Risk ID": risk_id,
            "Priority": compute_risk_priority(risk, inputs, flags),
            "Source": classify_risk_source(risk_id),
            "Risk": risk["Fundamental rights risk"],
            "Status": "Open"
        })

    return pd.DataFrame(rows)


def build_mitigation_action_plan(risks, inputs, flags):
    rows = []

    for risk in risks:
        risk_id = risk["ID"]
        priority = compute_risk_priority(risk, inputs, flags)
        actions = suggested_actions_for_risk(risk_id)

        for action, evidence in actions:
            rows.append({
                "Risk ID": risk_id,
                "Priority": priority,
                "Action required": action,
                "Evidence to collect": evidence,
                "Suggested owner": suggest_owner_for_action(action),
                "Status": "To be started",
                "Deadline": "To be defined",
                "Evidence collected": "",
                "Residual risk after action": "To be verified"
            })

    return pd.DataFrame(rows)


def build_report(inputs, risks, flags, scrutiny_level, outcome, dpia_score, dpia_missing, coherence_warnings, final_decision_log):
    is_provider = is_provider_role(inputs)
    is_deployer = is_deployer_role(inputs)

    report = []

    report.append("# DPIA-based Fundamental Rights Assessment Report")
    report.append("")
    report.append(f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    report.append("")

    report.append("## 1. Assessment scope")
    report.append(f"- Project name: {inputs['project_name']}")
    report.append(f"- Organisation: {inputs['organisation']}")
    report.append(f"- Who is completing the assessment: {', '.join(inputs['filer_role'])}")
    report.append(f"- Accountability owner: {inputs['accountability_owner']}")
    report.append("")

    report.append("## 2. DPIA core analysis")
    report.append(f"- DPIA completeness score: {dpia_score}%")
    if dpia_missing:
        report.append(f"- Missing or weak DPIA elements: {', '.join(dpia_missing)}")
    else:
        report.append("- Missing or weak DPIA elements: none")
    report.append("")
    report.append("### 2.1 Processing description")
    report.append(f"- Purpose: {inputs['purpose']}")
    report.append(f"- Processing operation: {inputs['processing_description']}")
    report.append(f"- Operational and organisational context: {inputs['processing_context']}")
    report.append("")
    report.append("### 2.2 Legal basis, purpose limitation and compatibility")
    report.append(f"- Legal basis: {inputs['legal_basis']}")
    report.append(f"- Purpose specific and explicit: {inputs['purpose_specificity']}")
    report.append(f"- Legal basis adequate: {inputs['legal_basis_adequacy']}")
    report.append(f"- Purpose compatibility assessed: {inputs['purpose_compatibility']}")
    report.append(f"- Legal basis reasoning: {inputs['legal_basis_reasoning']}")
    report.append(f"- Compatibility reasoning: {inputs['compatibility_reasoning']}")
    report.append("")
    report.append("### 2.3 Data categories, minimisation and retention")
    report.append(f"- Data categories: {', '.join(inputs['data_categories'])}")
    report.append(f"- Data sources: {', '.join(inputs['data_sources'])}")
    report.append(f"- Data strictly necessary: {inputs['data_necessary']}")
    report.append(f"- Data minimisation demonstrated: {inputs['data_minimisation']}")
    report.append(f"- Retention limits defined: {inputs['retention_limits']}")
    report.append(f"- Data minimisation reasoning: {inputs['data_minimisation_reasoning']}")
    report.append(f"- Retention reasoning: {inputs['retention_reasoning']}")
    report.append("")
    report.append("### 2.4 Data subjects, vulnerabilities and power asymmetries")
    report.append(f"- Categories of data subjects: {', '.join(inputs['data_subjects'])}")
    report.append(f"- Vulnerable persons or groups involved: {inputs['vulnerable_subjects']}")
    report.append(f"- Power asymmetry present: {inputs['power_asymmetry']}")
    report.append(f"- Vulnerability/power-asymmetry reasoning: {inputs['vulnerability_reasoning']}")
    report.append("")
    report.append("### 2.5 Transparency and data-subject rights")
    report.append(f"- Transparency notice: {inputs['transparency_notice']}")
    report.append(f"- Data-subject rights supported: {', '.join(inputs['data_subject_rights'])}")
    report.append(f"- Rights-exercise notes: {inputs['rights_exercise_notes']}")
    report.append("")
    report.append("### 2.6 DPIA necessity and proportionality baseline")
    report.append(f"- Less intrusive alternatives assessed: {inputs['alternatives_assessed']}")
    report.append(f"- Necessity reasoning: {inputs['necessity_reasoning']}")
    report.append(f"- Proportionality reasoning: {inputs['proportionality_reasoning']}")
    report.append("")
    report.append("### 2.7 DPIA baseline risk assessment")
    report.append(f"- Baseline DPIA risk to rights and freedoms: {inputs['dpia_risk_to_rights']}")
    report.append(f"- Processing remains likely high-risk after initial safeguards: {inputs['dpia_high_risk']}")
    report.append(f"- DPIA risk description: {inputs['dpia_risk_description']}")
    report.append("")

    report.append("## 3. Decision-making and fundamental-rights context")
    report.append(f"- Deployment context: {', '.join(inputs['contexts'])}")
    report.append(f"- System action: {', '.join(inputs['actions'])}")
    report.append(f"- Effect on persons, groups or opportunities: {inputs['decision_effect']}")
    report.append(f"- Affected persons or groups: {', '.join(inputs['groups'])}")
    report.append("")

    report.append("## 4. Mitigation measures")
    report.append("### 4.1 Data quality and data governance")
    report.append(f"- Data quality assessed: {inputs['data_quality_assessed']}")
    report.append(f"- Data quality measures: {', '.join(inputs['data_quality_measures'])}")
    report.append(f"- Bias/proxy-control safeguards: {inputs['bias_control']}")
    report.append(f"- Residual risk after data quality measures: {inputs['data_quality_residual_risk']}")
    report.append(f"- Data governance notes: {inputs['data_governance_notes']}")
    report.append("")
    report.append("### 4.2 Human oversight")
    report.append(f"- Human oversight: {inputs['human_oversight']}")
    report.append(f"- Human oversight measures: {', '.join(inputs['human_oversight_measures'])}")
    report.append(f"- Residual risk after human oversight measures: {inputs['human_oversight_residual_risk']}")
    report.append(f"- Human oversight notes: {inputs['human_oversight_notes']}")
    report.append("")
    report.append("### 4.3 Contestability and remedies")
    report.append(f"- Contestability: {inputs['contestability']}")
    report.append(f"- Remedy effectiveness: {inputs['remedy_effectiveness']}")
    report.append(f"- Contestability measures: {', '.join(inputs['contestability_measures'])}")
    report.append(f"- Fallback channel: {inputs['fallback_channel']}")
    report.append(f"- Residual risk after contestability measures: {inputs['contestability_residual_risk']}")
    report.append(f"- Affected groups consulted: {inputs['affected_groups_consulted']}")
    report.append(f"- Contestability notes: {inputs['contestability_notes']}")
    report.append("")
    report.append("### 4.4 Governance")
    report.append(f"- Governance notes: {inputs['governance_notes']}")
    report.append("")

    if is_provider:
        report.append("## 5A. Provider-side AI Act Article 9 add-on")
        report.append(f"- Continuous lifecycle review and updating: {inputs['provider_lifecycle_review']}")
        report.append(f"- Known and foreseeable health/safety risk: {inputs['provider_health_safety_risk']}")
        report.append(f"- Known and foreseeable fundamental-rights risk: {inputs['provider_fr_risk']}")
        report.append(f"- Risk under intended purpose: {inputs['provider_intended_purpose_risk']}")
        report.append(f"- Risk under reasonably foreseeable misuse: {inputs['provider_misuse_risk']}")
        report.append(f"- Reasonably foreseeable misuse assessed: {inputs['misuse_assessed']}")
        report.append(f"- Post-market monitoring feedback linked to risk review: {inputs['provider_post_market_link']}")
        report.append(f"- Targeted risk-management measures adopted: {inputs['provider_targeted_measures']}")
        report.append(f"- Residual risk defined and documented: {inputs['residual_risk_defined']}")
        report.append(f"- Provider-side notes: {inputs['provider_article9_notes']}")
        report.append("")

    if is_deployer:
        report.append("## 5B. Deployer-side AI Act Article 27 add-on")
        report.append(f"- Deployer process description: {inputs['deployer_process_description']}")
        report.append(f"- Expected period of use: {inputs['deployment_period']}")
        report.append(f"- Expected frequency of use: {inputs['deployment_frequency']}")
        report.append(f"- Affected categories described: {inputs['affected_categories_described']}")
        report.append(f"- Provider Article 13 information used: {inputs['provider_article13_info_used']}")
        report.append(f"- Specific risks of harm in context: {inputs['deployer_specific_harms']}")
        report.append(f"- Human oversight implemented according to instructions: {inputs['deployer_human_oversight_according_to_instructions']}")
        report.append(f"- Measures if risks materialise: {inputs['risk_materialisation_measures']}")
        report.append(f"- Internal governance and complaint mechanisms: {inputs['deployer_governance_complaints']}")
        report.append(f"- Post-deployment monitoring: {inputs['monitoring']}")
        report.append("")

    report.append("## 6. Fundamental rights risks selected")
    if not risks:
        report.append("No risk automatically activated. Manual legal review is required.")
    else:
        for risk in risks:
            report.append(f"### {risk['ID']} - {risk['Fundamental rights risk']}")
            report.append(f"- Rights involved: {risk['Rights involved']}")
            report.append(f"- Legal mechanisms of harm: {risk['Legal mechanisms of harm']}")
            report.append(f"- Triggered by: {risk['Triggered by']}")
            report.append(f"- Questions for legal analysis: {risk['Questions for legal analysis']}")
            report.append(f"- Safeguards to test: {risk['Safeguards to test']}")
            report.append("")

    report.append("## 6B. Operational use of the risk register")
    report.append(
        "The fundamental-rights risk register is not merely descriptive. "
        "It operates as a working governance register connecting each identified risk "
        "to its assessment source, priority, required safeguards, mitigation evidence, "
        "responsible owner and residual-risk decision."
    )
    report.append("")

    report.append("## 7. Red flags and coherence warnings")
    if not flags:
        report.append("No red flags detected.")
    else:
        for level, message in flags:
            report.append(f"- [{level}] {message}")

    if coherence_warnings:
        for warning in coherence_warnings:
            report.append(f"- [COHERENCE] {warning}")
    report.append("")

    report.append("## 8. Scrutiny and recommended outcome")
    report.append(f"- Scrutiny level: {scrutiny_level}")
    report.append(f"- Recommended outcome: {outcome}")
    report.append("")

    report.append("## 9. Final governance decision log")
    report.append(f"- Final decision: {final_decision_log['Final decision']}")
    report.append(f"- Decision-maker: {final_decision_log['Decision-maker']}")
    report.append(f"- Conditions for deployment: {final_decision_log['Conditions for deployment']}")
    report.append(f"- Decision reasoning: {final_decision_log['Decision reasoning']}")
    report.append(f"- Review date: {final_decision_log['Review date']}")
    report.append("")

    report.append("## Methodological note")
    report.append(
        "This tool does not automate constitutional judgment. It starts from a full DPIA core analysis. "
        "The DPIA operates as the common procedural backbone: it describes the processing, tests legal basis, "
        "purpose limitation, data minimisation, transparency, data-subject rights, necessity, proportionality "
        "and baseline risk to rights and freedoms. Article 9 and Article 27 are then added only as role-specific "
        "AI Act modules, without duplicating the DPIA. Their function is to feed the fundamental-rights risk "
        "selection layer with AI Act-specific information. The mitigation layer tests whether identified risks "
        "are addressed through three minimum safeguards: data quality, meaningful human oversight and effective contestability."
    )

    return "\n".join(report)


# ---------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------

with st.expander("Methodological logic", expanded=True):
    st.markdown(
        """
        This tool starts from a **full DPIA core analysis**.

        The DPIA operates as the **common procedural backbone**. It describes the processing
        operation and tests:

        - legal basis;
        - purpose limitation and compatibility;
        - data minimisation;
        - data-subject categories and vulnerabilities;
        - transparency and data-subject rights;
        - necessity and proportionality;
        - baseline risk to rights and freedoms.

        The tool then adds a **fundamental-rights legal risk selection layer**, focused on:

        - the decision-making context;
        - persons and groups affected;
        - legal mechanisms of harm;
        - safeguards, remedies and accountability.

        The mitigation layer tests whether identified risks are addressed through three minimum safeguards:

        - **data quality**;
        - **meaningful human oversight**;
        - **effective contestability**.

        **Provider-side Article 9 add-on** opens only if the filer includes a provider role.
        It asks about health and safety risk, fundamental-rights risk, intended purpose,
        reasonably foreseeable misuse, post-market monitoring and targeted risk-management measures.

        **Deployer-side Article 27 add-on** opens only if the filer includes a deployer role.
        It focuses on the specific deployment process, period and frequency of use,
        affected categories, specific harms, human oversight, governance and complaint mechanisms.

        Article 9 and Article 27 do **not** duplicate the DPIA. They only add role-specific
        AI Act features that feed the fundamental-rights analysis.
        """
    )

with st.form("assessment_form"):
    st.header("1. Assessment scope")

    col1, col2 = st.columns(2)

    with col1:
        project_name = st.text_input("Project name", "Recruitment AI Pilot")
        organisation = st.text_input("Organisation", "Example organisation")
        filer_role = st.multiselect(
            "Who is completing this assessment?",
            FILER_ROLES,
            default=["Controller / data protection team"]
        )

    with col2:
        accountability_owner = st.text_input("Accountability owner", "DPO / AI Governance Officer")
        legal_basis = st.selectbox("Legal basis", LEGAL_BASES)
        data_necessary = st.selectbox("Are data strictly necessary for the stated purpose?", YES_NO_OPTIONS)

    st.header("2. DPIA core analysis")

    st.markdown(
        """
        This section is the procedural backbone of the assessment. It describes the processing
        and tests purpose limitation, legal basis, necessity, minimisation, transparency
        and data-subject rights.
        """
    )

    st.subheader("2.1 Processing description")

    purpose = st.text_area(
        "Purpose of the processing / AI use",
        "",
        placeholder=(
            "Describe the specific, explicit and legitimate purpose of the processing "
            "and explain how the AI system contributes to that purpose."
        )
    )

    processing_description = st.text_area(
        "Systematic description of the processing operation",
        "",
        placeholder=(
            "Describe the processing lifecycle: data collection, data sources, input data, "
            "model use, output generation, human decision-making, storage, sharing and deletion."
        )
    )

    processing_context = st.text_area(
        "Operational and organisational context",
        "",
        placeholder=(
            "Describe the organisational process in which the processing takes place, "
            "the actors involved and the practical setting of the decision."
        )
    )

    st.subheader("2.2 Legal basis, purpose limitation and compatibility")

    col3, col4 = st.columns(2)

    with col3:
        purpose_specificity = st.selectbox(
            "Is the purpose specific, explicit and sufficiently determined?",
            YES_NO_OPTIONS
        )

        legal_basis_adequacy = st.selectbox(
            "Is the selected legal basis adequate for this processing operation?",
            YES_NO_OPTIONS
        )

        purpose_compatibility = st.selectbox(
            "If data are reused, has compatibility with the original purpose been assessed?",
            YES_NO_NA_OPTIONS
        )

    with col4:
        legal_basis_reasoning = st.text_area(
            "Legal basis reasoning",
            "",
            placeholder=(
                "Explain why the selected legal basis applies, including any relevant balancing "
                "or public-interest justification."
            )
        )

        compatibility_reasoning = st.text_area(
            "Purpose limitation / compatibility reasoning",
            "",
            placeholder=(
                "Explain whether the processing is compatible with the original collection purpose "
                "and whether further processing creates additional risks."
            )
        )

    st.subheader("2.3 Data categories, minimisation and retention")

    data_categories = st.multiselect(
        "Data categories",
        DATA_CATEGORIES,
        default=["Common personal data"]
    )

    col5, col6 = st.columns(2)

    with col5:
        data_sources = st.multiselect("Data sources", DATA_SOURCES, default=[])

        data_minimisation = st.selectbox(
            "Are the data limited to what is necessary for the purpose?",
            YES_NO_OPTIONS
        )

        retention_limits = st.selectbox(
            "Are storage limitation and deletion periods defined?",
            YES_NO_OPTIONS
        )

    with col6:
        data_minimisation_reasoning = st.text_area(
            "Data minimisation reasoning",
            "",
            placeholder=(
                "Explain why each data category is necessary and whether less data, less granular data "
                "or shorter retention would achieve the same purpose."
            )
        )

        retention_reasoning = st.text_area(
            "Retention reasoning",
            "",
            placeholder="Explain retention periods, deletion rules and any archiving or logging needs."
        )

    st.subheader("2.4 Data subjects, vulnerabilities and power asymmetries")

    col7, col8 = st.columns(2)

    with col7:
        data_subjects = st.multiselect(
            "Categories of data subjects",
            GROUPS,
            default=["Workers/candidates"]
        )

        vulnerable_subjects = st.selectbox(
            "Are vulnerable persons or groups involved?",
            YES_NO_OPTIONS
        )

        power_asymmetry = st.selectbox(
            "Is there a significant power asymmetry between the organisation and affected persons?",
            YES_NO_OPTIONS
        )

    with col8:
        vulnerability_reasoning = st.text_area(
            "Vulnerability and power-asymmetry reasoning",
            "",
            placeholder=(
                "Explain whether the affected persons are workers, students, patients, welfare recipients, "
                "children, migrants or other persons in a dependent or vulnerable position."
            )
        )

    st.subheader("2.5 Transparency and data-subject rights")

    col9, col10 = st.columns(2)

    with col9:
        transparency_notice = st.selectbox(
            "Are affected persons informed in a clear and understandable way?",
            YES_NO_OPTIONS
        )

        data_subject_rights = st.multiselect(
            "Which data-subject rights are operationally supported?",
            DATA_SUBJECT_RIGHTS,
            default=["None / to be defined"]
        )

    with col10:
        rights_exercise_notes = st.text_area(
            "Transparency and rights-exercise notes",
            "",
            placeholder=(
                "Explain how affected persons are informed and how they can exercise their rights "
                "in practice, including deadlines, channels and responsible teams."
            )
        )

    st.subheader("2.6 DPIA necessity and proportionality baseline")

    col11, col12 = st.columns(2)

    with col11:
        alternatives_assessed = st.selectbox(
            "Have less intrusive alternatives been assessed?",
            YES_NO_OPTIONS
        )

        necessity_reasoning = st.text_area(
            "Necessity reasoning",
            "",
            placeholder=(
                "Why is this processing necessary? Why this system, these data and this degree of automation? "
                "Could the purpose be achieved with a less intrusive measure?"
            )
        )

    with col12:
        proportionality_reasoning = st.text_area(
            "Proportionality reasoning",
            "",
            placeholder=(
                "Which concrete benefits justify the risks? Who benefits, who bears the risk, "
                "and is the residual impact acceptable?"
            )
        )

    st.subheader("2.7 DPIA baseline risk assessment")

    col13, col14 = st.columns(2)

    with col13:
        dpia_risk_to_rights = st.selectbox(
            "Baseline risk to rights and freedoms under the DPIA",
            RISK_LEVELS
        )

        dpia_high_risk = st.selectbox(
            "Does the processing remain likely to result in high risk after initial safeguards?",
            YES_NO_OPTIONS
        )

    with col14:
        dpia_risk_description = st.text_area(
            "DPIA risk description",
            "",
            placeholder=(
                "Describe the main risks to rights and freedoms arising from the processing itself, "
                "before adding provider/deployer-specific AI Act features."
            )
        )

    st.header("3. Decision-making and fundamental-rights context")

    col15, col16 = st.columns(2)

    with col15:
        contexts = st.multiselect(
            "Deployment context",
            CONTEXTS,
            default=["Employment/HR"]
        )

        actions = st.multiselect(
            "System action",
            ACTIONS,
            default=["Scoring/ranking"]
        )

    with col16:
        decision_effect = st.selectbox(
            "Effect on persons, groups or opportunities",
            DECISION_EFFECTS
        )

        groups = st.multiselect(
            "Affected persons or groups",
            GROUPS,
            default=["Workers/candidates"]
        )

    st.header("4. Mitigation measures: data quality, human oversight and contestability")

    st.markdown(
        """
        This section tests whether fundamental-rights risks are actually mitigated.
        It focuses on three minimum safeguards: **data quality**, **meaningful human oversight**,
        and **effective contestability**.
        """
    )

    st.subheader("4.1 Data quality and data governance")

    col17, col18 = st.columns(2)

    with col17:
        data_quality_assessed = st.selectbox(
            "Has data quality been assessed?",
            YES_NO_OPTIONS
        )

        data_quality_measures = st.multiselect(
            "Which data quality measures are in place?",
            DATA_QUALITY_MEASURES,
            default=["None / to be defined"]
        )

        data_quality_residual_risk = st.selectbox(
            "Residual risk after data quality measures",
            RISK_LEVELS
        )

    with col18:
        bias_control = st.selectbox(
            "Are bias and proxy-discrimination safeguards demonstrated?",
            YES_NO_OPTIONS
        )

        data_governance_notes = st.text_area(
            "Data quality and governance notes",
            "",
            placeholder=(
                "Explain data sources, representativeness, known limitations, "
                "bias/proxy controls, error correction and residual risk."
            )
        )

    st.subheader("4.2 Human oversight")

    col19, col20 = st.columns(2)

    with col19:
        human_oversight = st.selectbox(
            "Is there meaningful human oversight?",
            ["Effective", "Merely formal", "Absent", "Not applicable", "To be verified"]
        )

        human_oversight_measures = st.multiselect(
            "Which human oversight measures are in place?",
            HUMAN_OVERSIGHT_MEASURES,
            default=["None / to be defined"]
        )

        human_oversight_residual_risk = st.selectbox(
            "Residual risk after human oversight measures",
            RISK_LEVELS
        )

    with col20:
        human_oversight_notes = st.text_area(
            "Human oversight notes",
            "",
            placeholder=(
                "Explain who reviews the output, when, with what authority, "
                "whether they can override the system, and how automation bias is prevented."
            )
        )

    st.subheader("4.3 Contestability, remedy and complaint mechanisms")

    col21, col22 = st.columns(2)

    with col21:
        contestability = st.selectbox(
            "Can affected persons contest the outcome?",
            YES_NO_OPTIONS
        )

        remedy_effectiveness = st.selectbox(
            "Is the remedy capable of changing the outcome?",
            YES_NO_OPTIONS
        )

        contestability_measures = st.multiselect(
            "Which contestability measures are in place?",
            CONTESTABILITY_MEASURES,
            default=["None / to be defined"]
        )

    with col22:
        fallback_channel = st.selectbox(
            "Is there a reliable non-automated or alternative channel where needed?",
            YES_NO_OPTIONS
        )

        contestability_residual_risk = st.selectbox(
            "Residual risk after contestability measures",
            RISK_LEVELS
        )

        affected_groups_consulted = st.selectbox(
            "Have affected groups or representatives been consulted?",
            YES_NO_NA_OPTIONS
        )

    contestability_notes = st.text_area(
        "Contestability and remedy notes",
        "",
        placeholder=(
            "Explain how affected persons are informed, how they can contest, "
            "whether contestation can change the outcome, and how complaints are handled."
        )
    )

    st.subheader("4.4 Governance of mitigation measures")

    governance_notes = st.text_area(
        "Governance and accountability notes",
        "",
        placeholder=(
            "Who owns each mitigation measure? Who monitors effectiveness? "
            "Who updates the assessment? Who is accountable for residual risk?"
        )
    )

    show_provider_module = (
        "Provider" in filer_role
        or "Joint assessment team" in filer_role
    )

    show_deployer_module = (
        "Deployer" in filer_role
        or "Joint assessment team" in filer_role
    )

    if show_provider_module:
        st.header("5A. Provider-side AI Act Article 9 add-on")
        st.caption(
            "This section opens because the filer includes a provider role. "
            "It captures Article 9-specific risk-management features without duplicating the DPIA."
        )

        st.markdown(
            "**Article 9 logic:** identify and analyse known and reasonably foreseeable risks "
            "to health, safety and fundamental rights; estimate risk under intended purpose and "
            "foreseeable misuse; evaluate risks emerging from post-market monitoring; adopt "
            "targeted risk-management measures."
        )

        col23, col24 = st.columns(2)

        with col23:
            provider_lifecycle_review = st.selectbox(
                "Is the risk-management system continuous, iterative and updated across the lifecycle?",
                YES_NO_OPTIONS
            )

            provider_health_safety_risk = st.selectbox(
                "Known or reasonably foreseeable risk to health or safety",
                RISK_LEVELS
            )

            provider_fr_risk = st.selectbox(
                "Known or reasonably foreseeable risk to fundamental rights",
                RISK_LEVELS
            )

            provider_intended_purpose_risk = st.selectbox(
                "Risk when used according to intended purpose",
                RISK_LEVELS
            )

        with col24:
            provider_misuse_risk = st.selectbox(
                "Risk under reasonably foreseeable misuse",
                RISK_LEVELS
            )

            misuse_assessed = st.selectbox(
                "Has reasonably foreseeable misuse been specifically assessed?",
                YES_NO_OPTIONS
            )

            provider_post_market_link = st.selectbox(
                "Are risks from post-market monitoring linked back to risk review?",
                YES_NO_OPTIONS
            )

            provider_targeted_measures = st.selectbox(
                "Have appropriate and targeted risk-management measures been adopted?",
                YES_NO_OPTIONS
            )

        residual_risk_defined = st.selectbox(
            "Has residual risk been defined and documented?",
            YES_NO_OPTIONS
        )

        provider_article9_notes = st.text_area(
            "Provider-side Article 9 notes",
            "",
            placeholder=(
                "Explain health/safety risks, fundamental-rights risks, misuse scenarios, "
                "post-market feedback, targeted measures and residual risk."
            )
        )

    else:
        provider_lifecycle_review = "Not applicable"
        provider_health_safety_risk = "Not applicable"
        provider_fr_risk = "Not applicable"
        provider_intended_purpose_risk = "Not applicable"
        provider_misuse_risk = "Not applicable"
        misuse_assessed = "Not applicable"
        provider_post_market_link = "Not applicable"
        provider_targeted_measures = "Not applicable"
        residual_risk_defined = "Not applicable"
        provider_article9_notes = "Not applicable"

    if show_deployer_module:
        st.header("5B. Deployer-side AI Act Article 27 add-on")
        st.caption(
            "This section opens because the filer includes a deployer role. "
            "It captures deployment-specific FRIA features without duplicating the DPIA."
        )

        st.markdown(
            "**Article 27 logic:** describe the deployer process, period and frequency of use, "
            "categories of affected persons and groups, specific risks of harm in context, "
            "human oversight according to instructions, and measures in case risks materialise."
        )

        deployer_process_description = st.text_area(
            "Description of the deployer's process in which the high-risk AI system will be used",
            "",
            placeholder=(
                "Describe the organisational process, decision flow, human roles and operational setting."
            )
        )

        col25, col26 = st.columns(2)

        with col25:
            deployment_period = st.text_input(
                "Expected period of use",
                "To be verified"
            )

            deployment_frequency = st.selectbox(
                "Expected frequency of use",
                FREQUENCY_OPTIONS
            )

            affected_categories_described = st.selectbox(
                "Are categories of affected natural persons and groups described?",
                YES_NO_OPTIONS
            )

            provider_article13_info_used = st.selectbox(
                "Has provider information/instructions been used for this assessment?",
                YES_NO_OPTIONS
            )

        with col26:
            deployer_human_oversight_according_to_instructions = st.selectbox(
                "Is human oversight implemented according to the provider's instructions for use?",
                YES_NO_OPTIONS
            )

            risk_materialisation_measures = st.selectbox(
                "Are measures defined for the materialisation of risks?",
                YES_NO_OPTIONS
            )

            monitoring = st.selectbox(
                "Is post-deployment monitoring planned?",
                YES_NO_OPTIONS
            )

        deployer_specific_harms = st.text_area(
            "Specific risks of harm likely to affect the identified persons or groups",
            "",
            placeholder=(
                "Describe specific harms in this context, taking into account provider information, "
                "affected groups, frequency of use and organisational setting."
            )
        )

        deployer_governance_complaints = st.text_area(
            "Internal governance and complaint mechanisms",
            "",
            placeholder=(
                "Describe internal governance, complaint channels, escalation routes, deadlines, "
                "and measures to be taken if risks materialise."
            )
        )

    else:
        deployer_process_description = "Not applicable"
        deployment_period = "Not applicable"
        deployment_frequency = "Not applicable"
        affected_categories_described = "Not applicable"
        provider_article13_info_used = "Not applicable"
        deployer_human_oversight_according_to_instructions = "Not applicable"
        risk_materialisation_measures = "Not applicable"
        monitoring = "Not applicable"
        deployer_specific_harms = "Not applicable"
        deployer_governance_complaints = "Not applicable"

    submitted = st.form_submit_button("Generate fundamental rights assessment")


if submitted:
    inputs = {
        "project_name": project_name,
        "organisation": organisation,
        "filer_role": filer_role,
        "accountability_owner": accountability_owner,
        "legal_basis": legal_basis,
        "data_necessary": data_necessary,

        "purpose": purpose,
        "processing_description": processing_description,
        "processing_context": processing_context,
        "purpose_specificity": purpose_specificity,
        "legal_basis_adequacy": legal_basis_adequacy,
        "purpose_compatibility": purpose_compatibility,
        "legal_basis_reasoning": legal_basis_reasoning,
        "compatibility_reasoning": compatibility_reasoning,
        "data_categories": data_categories,
        "data_sources": data_sources,
        "data_minimisation": data_minimisation,
        "retention_limits": retention_limits,
        "data_minimisation_reasoning": data_minimisation_reasoning,
        "retention_reasoning": retention_reasoning,
        "data_subjects": data_subjects,
        "vulnerable_subjects": vulnerable_subjects,
        "power_asymmetry": power_asymmetry,
        "vulnerability_reasoning": vulnerability_reasoning,
        "transparency_notice": transparency_notice,
        "data_subject_rights": data_subject_rights,
        "rights_exercise_notes": rights_exercise_notes,
        "alternatives_assessed": alternatives_assessed,
        "necessity_reasoning": necessity_reasoning,
        "proportionality_reasoning": proportionality_reasoning,
        "dpia_risk_to_rights": dpia_risk_to_rights,
        "dpia_high_risk": dpia_high_risk,
        "dpia_risk_description": dpia_risk_description,

        "contexts": contexts,
        "actions": actions,
        "decision_effect": decision_effect,
        "groups": groups,

        "data_quality_assessed": data_quality_assessed,
        "data_quality_measures": data_quality_measures,
        "data_quality_residual_risk": data_quality_residual_risk,
        "data_governance_notes": data_governance_notes,
        "human_oversight": human_oversight,
        "human_oversight_measures": human_oversight_measures,
        "human_oversight_residual_risk": human_oversight_residual_risk,
        "human_oversight_notes": human_oversight_notes,
        "contestability": contestability,
        "remedy_effectiveness": remedy_effectiveness,
        "contestability_measures": contestability_measures,
        "contestability_residual_risk": contestability_residual_risk,
        "fallback_channel": fallback_channel,
        "contestability_notes": contestability_notes,
        "bias_control": bias_control,
        "affected_groups_consulted": affected_groups_consulted,
        "governance_notes": governance_notes,

        "provider_lifecycle_review": provider_lifecycle_review,
        "provider_health_safety_risk": provider_health_safety_risk,
        "provider_fr_risk": provider_fr_risk,
        "provider_intended_purpose_risk": provider_intended_purpose_risk,
        "provider_misuse_risk": provider_misuse_risk,
        "misuse_assessed": misuse_assessed,
        "provider_post_market_link": provider_post_market_link,
        "provider_targeted_measures": provider_targeted_measures,
        "residual_risk_defined": residual_risk_defined,
        "provider_article9_notes": provider_article9_notes,

        "deployer_process_description": deployer_process_description,
        "deployment_period": deployment_period,
        "deployment_frequency": deployment_frequency,
        "affected_categories_described": affected_categories_described,
        "provider_article13_info_used": provider_article13_info_used,
        "deployer_human_oversight_according_to_instructions": deployer_human_oversight_according_to_instructions,
        "risk_materialisation_measures": risk_materialisation_measures,
        "monitoring": monitoring,
        "deployer_specific_harms": deployer_specific_harms,
        "deployer_governance_complaints": deployer_governance_complaints
    }

    risks = activate_fundamental_rights_risks(inputs)
    flags = compute_red_flags(inputs, risks)
    scrutiny_level = compute_scrutiny_level(inputs, flags, risks)
    outcome = compute_outcome(flags, scrutiny_level)
    dpia_score, dpia_missing = compute_dpia_completeness(inputs)
    coherence_warnings = compute_coherence_warnings(inputs)

    final_decision_log = {
        "Final decision": "To be decided",
        "Decision-maker": "",
        "Conditions for deployment": "",
        "Decision reasoning": "",
        "Review date": ""
    }

    report = build_report(
        inputs,
        risks,
        flags,
        scrutiny_level,
        outcome,
        dpia_score,
        dpia_missing,
        coherence_warnings,
        final_decision_log
    )

    st.session_state["last_assessment"] = {
        "inputs": inputs,
        "risks": risks,
        "flags": flags,
        "scrutiny_level": scrutiny_level,
        "outcome": outcome,
        "dpia_score": dpia_score,
        "dpia_missing": dpia_missing,
        "coherence_warnings": coherence_warnings,
        "final_decision_log": final_decision_log,
        "report": report
    }


# ---------------------------------------------------------------------
# OUTPUT
# ---------------------------------------------------------------------

if "last_assessment" in st.session_state:
    result = st.session_state["last_assessment"]

    st.divider()
    st.header("Assessment result")

    col_a, col_b, col_c, col_d = st.columns(4)

    with col_a:
        st.metric("DPIA completeness", f"{result['dpia_score']}%")

    with col_b:
        st.metric("FR risks selected", len(result["risks"]))

    with col_c:
        st.metric("Red flags", len(result["flags"]))

    with col_d:
        st.metric("Scrutiny level", result["scrutiny_level"])

    if result["dpia_missing"]:
        with st.expander("Missing or weak DPIA elements", expanded=False):
            for item in result["dpia_missing"]:
                st.write("-", item)

    st.subheader("Recommended outcome")
    st.markdown(f"**{result['outcome']}**")

    st.subheader("Coherence warnings")

    if result["coherence_warnings"]:
        for warning in result["coherence_warnings"]:
            st.warning(warning)
    else:
        st.success("No coherence warnings detected.")

    st.subheader("Red flags")

    if not result["flags"]:
        st.success("No red flags detected.")
    else:
        for level, message in result["flags"]:
            if level == "BLOCKING":
                st.error(f"{level}: {message}")
            elif level == "HIGH":
                st.warning(f"{level}: {message}")
            else:
                st.info(f"{level}: {message}")

    st.subheader("Summary Fundamental Rights Risk Register")

    if result["risks"]:
        summary_register = build_summary_risk_register(
            result["risks"],
            result["inputs"],
            result["flags"]
        )
        st.dataframe(summary_register, use_container_width=True)
    else:
        st.info("No risk automatically activated. Manual legal review is required.")

    with st.expander("Operational Fundamental Rights Risk Register", expanded=False):
        if result["risks"]:
            operational_register = build_operational_risk_register(
                result["risks"],
                result["inputs"],
                result["flags"]
            )
            st.dataframe(operational_register, use_container_width=True)
        else:
            st.info("No operational risk register generated.")

    st.subheader("Editable Mitigation Action Plan")

    if result["risks"]:
        mitigation_plan = build_mitigation_action_plan(
            result["risks"],
            result["inputs"],
            result["flags"]
        )

        edited_mitigation_plan = st.data_editor(
            mitigation_plan,
            use_container_width=True,
            num_rows="dynamic",
            column_config={
                "Status": st.column_config.SelectboxColumn(
                    "Status",
                    options=ACTION_STATUSES,
                    required=True
                ),
                "Residual risk after action": st.column_config.SelectboxColumn(
                    "Residual risk after action",
                    options=RISK_LEVELS,
                    required=True
                )
            }
        )
        st.session_state["edited_mitigation_plan"] = edited_mitigation_plan
    else:
        st.info("No mitigation action plan generated.")

    st.subheader("Final governance decision log")

    col_decision_1, col_decision_2 = st.columns(2)

    with col_decision_1:
        final_decision = st.selectbox(
            "Final governance decision",
            GOVERNANCE_DECISIONS,
            index=GOVERNANCE_DECISIONS.index("To be decided")
        )

        decision_maker = st.text_input(
            "Decision-maker / governance body",
            ""
        )

        review_date = st.text_input(
            "Review date",
            ""
        )

    with col_decision_2:
        conditions_for_deployment = st.text_area(
            "Conditions for deployment",
            "",
            placeholder="List mandatory safeguards, escalation duties, or deployment conditions."
        )

        decision_reasoning = st.text_area(
            "Decision reasoning",
            "",
            placeholder="Explain why the residual risk is accepted, rejected or requires redesign."
        )

    final_decision_log = {
        "Final decision": final_decision,
        "Decision-maker": decision_maker,
        "Conditions for deployment": conditions_for_deployment,
        "Decision reasoning": decision_reasoning,
        "Review date": review_date
    }

    st.session_state["last_assessment"]["final_decision_log"] = final_decision_log

    st.subheader("Download report")

    safe_file_name = (
        result["inputs"]["project_name"]
        .lower()
        .replace(" ", "_")
        .replace("/", "_")
    )

    operational_register = pd.DataFrame()
    summary_register = pd.DataFrame()
    mitigation_plan_download = pd.DataFrame()

    if result["risks"]:
        operational_register = build_operational_risk_register(
            result["risks"],
            result["inputs"],
            result["flags"]
        )

        summary_register = build_summary_risk_register(
            result["risks"],
            result["inputs"],
            result["flags"]
        )

        mitigation_plan_download = st.session_state.get(
            "edited_mitigation_plan",
            build_mitigation_action_plan(
                result["risks"],
                result["inputs"],
                result["flags"]
            )
        )

        st.download_button(
            "Download Summary Risk Register CSV",
            summary_register.to_csv(index=False),
            file_name=f"{safe_file_name}_summary_risk_register.csv",
            mime="text/csv"
        )

        st.download_button(
            "Download Operational Risk Register CSV",
            operational_register.to_csv(index=False),
            file_name=f"{safe_file_name}_operational_risk_register.csv",
            mime="text/csv"
        )

        st.download_button(
            "Download Mitigation Action Plan CSV",
            mitigation_plan_download.to_csv(index=False),
            file_name=f"{safe_file_name}_mitigation_action_plan.csv",
            mime="text/csv"
        )

    updated_report = build_report(
        result["inputs"],
        result["risks"],
        result["flags"],
        result["scrutiny_level"],
        result["outcome"],
        result["dpia_score"],
        result["dpia_missing"],
        result["coherence_warnings"],
        final_decision_log
    )

    st.download_button(
        "Download Markdown report",
        updated_report,
        file_name=f"{safe_file_name}_fundamental_rights_assessment.md",
        mime="text/markdown"
    )

    json_payload = {
        "inputs": result["inputs"],
        "risks": result["risks"],
        "flags": result["flags"],
        "scrutiny_level": result["scrutiny_level"],
        "outcome": result["outcome"],
        "dpia_score": result["dpia_score"],
        "dpia_missing": result["dpia_missing"],
        "coherence_warnings": result["coherence_warnings"],
        "final_decision_log": final_decision_log,
        "generated_at": datetime.now().isoformat()
    }

    st.download_button(
        "Download JSON assessment",
        json.dumps(json_payload, ensure_ascii=False, indent=2),
        file_name=f"{safe_file_name}_assessment.json",
        mime="application/json"
    )